// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve.proxmox.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DiskBandwidth {
    /**
     * @return Read I/O operations per second limit (0 = unlimited).
     * 
     */
    private @Nullable Integer iopsRd;
    /**
     * @return Read burst I/O operations per second limit.
     * 
     */
    private @Nullable Integer iopsRdMax;
    /**
     * @return Write I/O operations per second limit (0 = unlimited).
     * 
     */
    private @Nullable Integer iopsWr;
    /**
     * @return Write burst I/O operations per second limit.
     * 
     */
    private @Nullable Integer iopsWrMax;
    /**
     * @return Read throughput limit in MB/s (0 = unlimited).
     * 
     */
    private @Nullable Double mbpsRd;
    /**
     * @return Read burst throughput limit in MB/s; allows temporary bursts above MBpsRd.
     * 
     */
    private @Nullable Double mbpsRdMax;
    /**
     * @return Write throughput limit in MB/s (0 = unlimited).
     * 
     */
    private @Nullable Double mbpsWr;
    /**
     * @return Write burst throughput limit in MB/s; allows temporary bursts above MBpsWr.
     * 
     */
    private @Nullable Double mbpsWrMax;

    private DiskBandwidth() {}
    /**
     * @return Read I/O operations per second limit (0 = unlimited).
     * 
     */
    public Optional<Integer> iopsRd() {
        return Optional.ofNullable(this.iopsRd);
    }
    /**
     * @return Read burst I/O operations per second limit.
     * 
     */
    public Optional<Integer> iopsRdMax() {
        return Optional.ofNullable(this.iopsRdMax);
    }
    /**
     * @return Write I/O operations per second limit (0 = unlimited).
     * 
     */
    public Optional<Integer> iopsWr() {
        return Optional.ofNullable(this.iopsWr);
    }
    /**
     * @return Write burst I/O operations per second limit.
     * 
     */
    public Optional<Integer> iopsWrMax() {
        return Optional.ofNullable(this.iopsWrMax);
    }
    /**
     * @return Read throughput limit in MB/s (0 = unlimited).
     * 
     */
    public Optional<Double> mbpsRd() {
        return Optional.ofNullable(this.mbpsRd);
    }
    /**
     * @return Read burst throughput limit in MB/s; allows temporary bursts above MBpsRd.
     * 
     */
    public Optional<Double> mbpsRdMax() {
        return Optional.ofNullable(this.mbpsRdMax);
    }
    /**
     * @return Write throughput limit in MB/s (0 = unlimited).
     * 
     */
    public Optional<Double> mbpsWr() {
        return Optional.ofNullable(this.mbpsWr);
    }
    /**
     * @return Write burst throughput limit in MB/s; allows temporary bursts above MBpsWr.
     * 
     */
    public Optional<Double> mbpsWrMax() {
        return Optional.ofNullable(this.mbpsWrMax);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DiskBandwidth defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer iopsRd;
        private @Nullable Integer iopsRdMax;
        private @Nullable Integer iopsWr;
        private @Nullable Integer iopsWrMax;
        private @Nullable Double mbpsRd;
        private @Nullable Double mbpsRdMax;
        private @Nullable Double mbpsWr;
        private @Nullable Double mbpsWrMax;
        public Builder() {}
        public Builder(DiskBandwidth defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.iopsRd = defaults.iopsRd;
    	      this.iopsRdMax = defaults.iopsRdMax;
    	      this.iopsWr = defaults.iopsWr;
    	      this.iopsWrMax = defaults.iopsWrMax;
    	      this.mbpsRd = defaults.mbpsRd;
    	      this.mbpsRdMax = defaults.mbpsRdMax;
    	      this.mbpsWr = defaults.mbpsWr;
    	      this.mbpsWrMax = defaults.mbpsWrMax;
        }

        @CustomType.Setter
        public Builder iopsRd(@Nullable Integer iopsRd) {

            this.iopsRd = iopsRd;
            return this;
        }
        @CustomType.Setter
        public Builder iopsRdMax(@Nullable Integer iopsRdMax) {

            this.iopsRdMax = iopsRdMax;
            return this;
        }
        @CustomType.Setter
        public Builder iopsWr(@Nullable Integer iopsWr) {

            this.iopsWr = iopsWr;
            return this;
        }
        @CustomType.Setter
        public Builder iopsWrMax(@Nullable Integer iopsWrMax) {

            this.iopsWrMax = iopsWrMax;
            return this;
        }
        @CustomType.Setter
        public Builder mbpsRd(@Nullable Double mbpsRd) {

            this.mbpsRd = mbpsRd;
            return this;
        }
        @CustomType.Setter
        public Builder mbpsRdMax(@Nullable Double mbpsRdMax) {

            this.mbpsRdMax = mbpsRdMax;
            return this;
        }
        @CustomType.Setter
        public Builder mbpsWr(@Nullable Double mbpsWr) {

            this.mbpsWr = mbpsWr;
            return this;
        }
        @CustomType.Setter
        public Builder mbpsWrMax(@Nullable Double mbpsWrMax) {

            this.mbpsWrMax = mbpsWrMax;
            return this;
        }
        public DiskBandwidth build() {
            final var _resultValue = new DiskBandwidth();
            _resultValue.iopsRd = iopsRd;
            _resultValue.iopsRdMax = iopsRdMax;
            _resultValue.iopsWr = iopsWr;
            _resultValue.iopsWrMax = iopsWrMax;
            _resultValue.mbpsRd = mbpsRd;
            _resultValue.mbpsRdMax = mbpsRdMax;
            _resultValue.mbpsWr = mbpsWr;
            _resultValue.mbpsWrMax = mbpsWrMax;
            return _resultValue;
        }
    }
}
