# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['VxlanZoneArgs', 'VxlanZone']

@pulumi.input_type
class VxlanZoneArgs:
    def __init__(__self__, *,
                 ipam: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 dns: Optional[pulumi.Input[_builtins.str]] = None,
                 dns_zone: Optional[pulumi.Input[_builtins.str]] = None,
                 fabric: Optional[pulumi.Input[_builtins.str]] = None,
                 mtu: Optional[pulumi.Input[_builtins.int]] = None,
                 nodes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 peers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 reverse_dns: Optional[pulumi.Input[_builtins.str]] = None,
                 vxlan_port: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a VxlanZone resource.
        :param pulumi.Input[_builtins.str] ipam: IPAM plugin ID associated with this zone.
        :param pulumi.Input[_builtins.str] name: The unique VXLAN zone name.
        :param pulumi.Input[_builtins.str] dns: DNS plugin ID associated with this zone.
        :param pulumi.Input[_builtins.str] dns_zone: DNS zone/domain name used for host registrations.
        :param pulumi.Input[_builtins.str] fabric: SDN fabric identifier used to connect this VXLAN zone to an EVPN fabric.
        :param pulumi.Input[_builtins.int] mtu: MTU for the VXLAN zone. If unset, Proxmox uses its automatic/default MTU.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] nodes: Cluster nodes where this zone is active.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] peers: A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
        :param pulumi.Input[_builtins.str] reverse_dns: Reverse DNS plugin ID associated with this zone.
        :param pulumi.Input[_builtins.int] vxlan_port: UDP destination port used for VXLAN encapsulation.
        """
        pulumi.set(__self__, "ipam", ipam)
        pulumi.set(__self__, "name", name)
        if dns is not None:
            pulumi.set(__self__, "dns", dns)
        if dns_zone is not None:
            pulumi.set(__self__, "dns_zone", dns_zone)
        if fabric is not None:
            pulumi.set(__self__, "fabric", fabric)
        if mtu is not None:
            pulumi.set(__self__, "mtu", mtu)
        if nodes is not None:
            pulumi.set(__self__, "nodes", nodes)
        if peers is not None:
            pulumi.set(__self__, "peers", peers)
        if reverse_dns is not None:
            pulumi.set(__self__, "reverse_dns", reverse_dns)
        if vxlan_port is None:
            vxlan_port = 4789
        if vxlan_port is not None:
            pulumi.set(__self__, "vxlan_port", vxlan_port)

    @_builtins.property
    @pulumi.getter
    def ipam(self) -> pulumi.Input[_builtins.str]:
        """
        IPAM plugin ID associated with this zone.
        """
        return pulumi.get(self, "ipam")

    @ipam.setter
    def ipam(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "ipam", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The unique VXLAN zone name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def dns(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        DNS plugin ID associated with this zone.
        """
        return pulumi.get(self, "dns")

    @dns.setter
    def dns(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "dns", value)

    @_builtins.property
    @pulumi.getter(name="dnsZone")
    def dns_zone(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        DNS zone/domain name used for host registrations.
        """
        return pulumi.get(self, "dns_zone")

    @dns_zone.setter
    def dns_zone(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "dns_zone", value)

    @_builtins.property
    @pulumi.getter
    def fabric(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SDN fabric identifier used to connect this VXLAN zone to an EVPN fabric.
        """
        return pulumi.get(self, "fabric")

    @fabric.setter
    def fabric(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "fabric", value)

    @_builtins.property
    @pulumi.getter
    def mtu(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        MTU for the VXLAN zone. If unset, Proxmox uses its automatic/default MTU.
        """
        return pulumi.get(self, "mtu")

    @mtu.setter
    def mtu(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "mtu", value)

    @_builtins.property
    @pulumi.getter
    def nodes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Cluster nodes where this zone is active.
        """
        return pulumi.get(self, "nodes")

    @nodes.setter
    def nodes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "nodes", value)

    @_builtins.property
    @pulumi.getter
    def peers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
        """
        return pulumi.get(self, "peers")

    @peers.setter
    def peers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "peers", value)

    @_builtins.property
    @pulumi.getter(name="reverseDns")
    def reverse_dns(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Reverse DNS plugin ID associated with this zone.
        """
        return pulumi.get(self, "reverse_dns")

    @reverse_dns.setter
    def reverse_dns(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "reverse_dns", value)

    @_builtins.property
    @pulumi.getter(name="vxlanPort")
    def vxlan_port(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        UDP destination port used for VXLAN encapsulation.
        """
        return pulumi.get(self, "vxlan_port")

    @vxlan_port.setter
    def vxlan_port(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "vxlan_port", value)


@pulumi.type_token("pve:vxlanzone:VxlanZone")
class VxlanZone(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 dns: Optional[pulumi.Input[_builtins.str]] = None,
                 dns_zone: Optional[pulumi.Input[_builtins.str]] = None,
                 fabric: Optional[pulumi.Input[_builtins.str]] = None,
                 ipam: Optional[pulumi.Input[_builtins.str]] = None,
                 mtu: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 nodes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 peers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 reverse_dns: Optional[pulumi.Input[_builtins.str]] = None,
                 vxlan_port: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        A Proxmox SDN VXLAN zone resource managed via /cluster/sdn/zones.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] dns: DNS plugin ID associated with this zone.
        :param pulumi.Input[_builtins.str] dns_zone: DNS zone/domain name used for host registrations.
        :param pulumi.Input[_builtins.str] fabric: SDN fabric identifier used to connect this VXLAN zone to an EVPN fabric.
        :param pulumi.Input[_builtins.str] ipam: IPAM plugin ID associated with this zone.
        :param pulumi.Input[_builtins.int] mtu: MTU for the VXLAN zone. If unset, Proxmox uses its automatic/default MTU.
        :param pulumi.Input[_builtins.str] name: The unique VXLAN zone name.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] nodes: Cluster nodes where this zone is active.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] peers: A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
        :param pulumi.Input[_builtins.str] reverse_dns: Reverse DNS plugin ID associated with this zone.
        :param pulumi.Input[_builtins.int] vxlan_port: UDP destination port used for VXLAN encapsulation.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VxlanZoneArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Proxmox SDN VXLAN zone resource managed via /cluster/sdn/zones.

        :param str resource_name: The name of the resource.
        :param VxlanZoneArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VxlanZoneArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 dns: Optional[pulumi.Input[_builtins.str]] = None,
                 dns_zone: Optional[pulumi.Input[_builtins.str]] = None,
                 fabric: Optional[pulumi.Input[_builtins.str]] = None,
                 ipam: Optional[pulumi.Input[_builtins.str]] = None,
                 mtu: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 nodes: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 peers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 reverse_dns: Optional[pulumi.Input[_builtins.str]] = None,
                 vxlan_port: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VxlanZoneArgs.__new__(VxlanZoneArgs)

            __props__.__dict__["dns"] = dns
            __props__.__dict__["dns_zone"] = dns_zone
            __props__.__dict__["fabric"] = fabric
            if ipam is None and not opts.urn:
                raise TypeError("Missing required property 'ipam'")
            __props__.__dict__["ipam"] = ipam
            __props__.__dict__["mtu"] = mtu
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["nodes"] = nodes
            __props__.__dict__["peers"] = peers
            __props__.__dict__["reverse_dns"] = reverse_dns
            if vxlan_port is None:
                vxlan_port = 4789
            __props__.__dict__["vxlan_port"] = vxlan_port
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["name"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(VxlanZone, __self__).__init__(
            'pve:vxlanzone:VxlanZone',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'VxlanZone':
        """
        Get an existing VxlanZone resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = VxlanZoneArgs.__new__(VxlanZoneArgs)

        __props__.__dict__["dns"] = None
        __props__.__dict__["dns_zone"] = None
        __props__.__dict__["fabric"] = None
        __props__.__dict__["ipam"] = None
        __props__.__dict__["mtu"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["nodes"] = None
        __props__.__dict__["peers"] = None
        __props__.__dict__["reverse_dns"] = None
        __props__.__dict__["vxlan_port"] = None
        return VxlanZone(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def dns(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        DNS plugin ID associated with this zone.
        """
        return pulumi.get(self, "dns")

    @_builtins.property
    @pulumi.getter(name="dnsZone")
    def dns_zone(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        DNS zone/domain name used for host registrations.
        """
        return pulumi.get(self, "dns_zone")

    @_builtins.property
    @pulumi.getter
    def fabric(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        SDN fabric identifier used to connect this VXLAN zone to an EVPN fabric.
        """
        return pulumi.get(self, "fabric")

    @_builtins.property
    @pulumi.getter
    def ipam(self) -> pulumi.Output[_builtins.str]:
        """
        IPAM plugin ID associated with this zone.
        """
        return pulumi.get(self, "ipam")

    @_builtins.property
    @pulumi.getter
    def mtu(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        MTU for the VXLAN zone. If unset, Proxmox uses its automatic/default MTU.
        """
        return pulumi.get(self, "mtu")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The unique VXLAN zone name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def nodes(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Cluster nodes where this zone is active.
        """
        return pulumi.get(self, "nodes")

    @_builtins.property
    @pulumi.getter
    def peers(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
        """
        return pulumi.get(self, "peers")

    @_builtins.property
    @pulumi.getter(name="reverseDns")
    def reverse_dns(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Reverse DNS plugin ID associated with this zone.
        """
        return pulumi.get(self, "reverse_dns")

    @_builtins.property
    @pulumi.getter(name="vxlanPort")
    def vxlan_port(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        UDP destination port used for VXLAN encapsulation.
        """
        return pulumi.get(self, "vxlan_port")

