// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.Vm.Inputs
{

    public sealed class VmCloneArgs : global::Pulumi.ResourceArgs
    {
        [Input("dataStoreId")]
        public Input<string>? DataStoreId { get; set; }

        [Input("fullClone")]
        public Input<bool>? FullClone { get; set; }

        [Input("node")]
        public Input<string>? Node { get; set; }

        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        [Input("vmId", required: true)]
        public Input<int> VmId { get; set; } = null!;

        public VmCloneArgs()
        {
        }
        public static new VmCloneArgs Empty => new VmCloneArgs();
    }
}
