// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.Vm.Outputs
{

    [OutputType]
    public sealed class Cpu
    {
        public readonly ImmutableArray<string> FlagsDisabled;
        public readonly ImmutableArray<string> FlagsEnabled;
        public readonly bool? Hidden;
        public readonly string? HvVendorId;
        public readonly string? PhysBits;
        public readonly string? Type;

        [OutputConstructor]
        private Cpu(
            ImmutableArray<string> flagsDisabled,

            ImmutableArray<string> flagsEnabled,

            bool? hidden,

            string? hvVendorId,

            string? physBits,

            string? type)
        {
            FlagsDisabled = flagsDisabled;
            FlagsEnabled = flagsEnabled;
            Hidden = hidden;
            HvVendorId = hvVendorId;
            PhysBits = physBits;
            Type = type;
        }
    }
}
