// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.Vm.Outputs
{

    /// <summary>
    /// EFI disk configuration for the virtual machine.
    /// </summary>
    [OutputType]
    public sealed class EfiDisk
    {
        public readonly string Efitype;
        public readonly string? Filename;
        public readonly string Storage;

        [OutputConstructor]
        private EfiDisk(
            string efitype,

            string? filename,

            string storage)
        {
            Efitype = efitype;
            Filename = filename;
            Storage = storage;
        }
    }
}
