// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.Vm
{
    [PveResourceType("pve:vm:VM")]
    public partial class VM : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Automatically start the VM when the host boots (1 to enable, 0 to disable).
        /// </summary>
        [Output("autostart")]
        public Output<int?> Autostart { get; private set; } = null!;

        /// <summary>
        /// Minimum memory for ballooning in megabytes (0 disables the balloon device).
        /// </summary>
        [Output("balloon")]
        public Output<int?> Balloon { get; private set; } = null!;

        /// <summary>
        /// Clone configuration for creating the VM from a source template or VM.
        /// </summary>
        [Output("clone")]
        public Output<Hctamu.Pve.Proxmox.Outputs.Clone?> Clone { get; private set; } = null!;

        /// <summary>
        /// CPU configuration including type, topology, and feature flags.
        /// </summary>
        [Output("cpu")]
        public Output<Hctamu.Pve.Proxmox.Outputs.CPU?> Cpu { get; private set; } = null!;

        /// <summary>
        /// Description or notes for the virtual machine.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// List of disk configurations attached to the virtual machine.
        /// </summary>
        [Output("disks")]
        public Output<ImmutableArray<Hctamu.Pve.Proxmox.Outputs.Disk>> Disks { get; private set; } = null!;

        /// <summary>
        /// EFI disk configuration (required when bios is set to ovmf).
        /// </summary>
        [Output("efidisk")]
        public Output<Hctamu.Pve.Proxmox.Outputs.EfiDisk?> Efidisk { get; private set; } = null!;

        /// <summary>
        /// Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
        /// </summary>
        [Output("hotplug")]
        public Output<string?> Hotplug { get; private set; } = null!;

        /// <summary>
        /// Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
        /// </summary>
        [Output("machine")]
        public Output<string?> Machine { get; private set; } = null!;

        /// <summary>
        /// Memory size in megabytes.
        /// </summary>
        [Output("memory")]
        public Output<int?> Memory { get; private set; } = null!;

        /// <summary>
        /// Name of the virtual machine.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Proxmox node where the VM resides.
        /// </summary>
        [Output("node")]
        public Output<string?> Node { get; private set; } = null!;

        /// <summary>
        /// Guest operating system type (e.g., l26, win11, other).
        /// </summary>
        [Output("ostype")]
        public Output<string?> Ostype { get; private set; } = null!;

        /// <summary>
        /// Tags associated with the virtual machine.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// Mark the VM as a template (1) or a regular VM (0).
        /// </summary>
        [Output("template")]
        public Output<int?> Template { get; private set; } = null!;

        /// <summary>
        /// Unique numeric identifier for the virtual machine (auto-assigned if omitted).
        /// </summary>
        [Output("vmId")]
        public Output<int?> VmId { get; private set; } = null!;


        /// <summary>
        /// Create a VM resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VM(string name, VMArgs args, CustomResourceOptions? options = null)
            : base("pve:vm:VM", name, args ?? new VMArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VM(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pve:vm:VM", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/hctamu/pulumi-pve",
                ReplaceOnChanges =
                {
                    "vmId",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VM resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VM Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new VM(name, id, options);
        }
    }

    public sealed class VMArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Automatically start the VM when the host boots (1 to enable, 0 to disable).
        /// </summary>
        [Input("autostart")]
        public Input<int>? Autostart { get; set; }

        /// <summary>
        /// Minimum memory for ballooning in megabytes (0 disables the balloon device).
        /// </summary>
        [Input("balloon")]
        public Input<int>? Balloon { get; set; }

        /// <summary>
        /// Clone configuration for creating the VM from a source template or VM.
        /// </summary>
        [Input("clone")]
        public Input<Hctamu.Pve.Proxmox.Inputs.CloneArgs>? Clone { get; set; }

        /// <summary>
        /// CPU configuration including type, topology, and feature flags.
        /// </summary>
        [Input("cpu")]
        public Input<Hctamu.Pve.Proxmox.Inputs.CPUArgs>? Cpu { get; set; }

        /// <summary>
        /// Description or notes for the virtual machine.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("disks", required: true)]
        private InputList<Hctamu.Pve.Proxmox.Inputs.DiskArgs>? _disks;

        /// <summary>
        /// List of disk configurations attached to the virtual machine.
        /// </summary>
        public InputList<Hctamu.Pve.Proxmox.Inputs.DiskArgs> Disks
        {
            get => _disks ?? (_disks = new InputList<Hctamu.Pve.Proxmox.Inputs.DiskArgs>());
            set => _disks = value;
        }

        /// <summary>
        /// EFI disk configuration (required when bios is set to ovmf).
        /// </summary>
        [Input("efidisk")]
        public Input<Hctamu.Pve.Proxmox.Inputs.EfiDiskArgs>? Efidisk { get; set; }

        /// <summary>
        /// Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
        /// </summary>
        [Input("hotplug")]
        public Input<string>? Hotplug { get; set; }

        /// <summary>
        /// Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
        /// </summary>
        [Input("machine")]
        public Input<string>? Machine { get; set; }

        /// <summary>
        /// Memory size in megabytes.
        /// </summary>
        [Input("memory")]
        public Input<int>? Memory { get; set; }

        /// <summary>
        /// Name of the virtual machine.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Proxmox node where the VM resides.
        /// </summary>
        [Input("node")]
        public Input<string>? Node { get; set; }

        /// <summary>
        /// Guest operating system type (e.g., l26, win11, other).
        /// </summary>
        [Input("ostype")]
        public Input<string>? Ostype { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// Tags associated with the virtual machine.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Mark the VM as a template (1) or a regular VM (0).
        /// </summary>
        [Input("template")]
        public Input<int>? Template { get; set; }

        /// <summary>
        /// Unique numeric identifier for the virtual machine (auto-assigned if omitted).
        /// </summary>
        [Input("vmId")]
        public Input<int>? VmId { get; set; }

        public VMArgs()
        {
        }
        public static new VMArgs Empty => new VMArgs();
    }
}
