// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vm

import (
	"context"
	"reflect"

	"github.com/hctamu/pulumi-pve/sdk/go/pve/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type Clone struct {
	DataStoreId *string `pulumi:"dataStoreId"`
	FullClone   *bool   `pulumi:"fullClone"`
	Node        *string `pulumi:"node"`
	Timeout     *int    `pulumi:"timeout"`
	VmId        int     `pulumi:"vmId"`
}

// CloneInput is an input type that accepts CloneArgs and CloneOutput values.
// You can construct a concrete instance of `CloneInput` via:
//
//	CloneArgs{...}
type CloneInput interface {
	pulumi.Input

	ToCloneOutput() CloneOutput
	ToCloneOutputWithContext(context.Context) CloneOutput
}

type CloneArgs struct {
	DataStoreId pulumi.StringPtrInput `pulumi:"dataStoreId"`
	FullClone   pulumi.BoolPtrInput   `pulumi:"fullClone"`
	Node        pulumi.StringPtrInput `pulumi:"node"`
	Timeout     pulumi.IntPtrInput    `pulumi:"timeout"`
	VmId        pulumi.IntInput       `pulumi:"vmId"`
}

func (CloneArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Clone)(nil)).Elem()
}

func (i CloneArgs) ToCloneOutput() CloneOutput {
	return i.ToCloneOutputWithContext(context.Background())
}

func (i CloneArgs) ToCloneOutputWithContext(ctx context.Context) CloneOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloneOutput)
}

func (i CloneArgs) ToClonePtrOutput() ClonePtrOutput {
	return i.ToClonePtrOutputWithContext(context.Background())
}

func (i CloneArgs) ToClonePtrOutputWithContext(ctx context.Context) ClonePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloneOutput).ToClonePtrOutputWithContext(ctx)
}

// ClonePtrInput is an input type that accepts CloneArgs, ClonePtr and ClonePtrOutput values.
// You can construct a concrete instance of `ClonePtrInput` via:
//
//	        CloneArgs{...}
//
//	or:
//
//	        nil
type ClonePtrInput interface {
	pulumi.Input

	ToClonePtrOutput() ClonePtrOutput
	ToClonePtrOutputWithContext(context.Context) ClonePtrOutput
}

type clonePtrType CloneArgs

func ClonePtr(v *CloneArgs) ClonePtrInput {
	return (*clonePtrType)(v)
}

func (*clonePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Clone)(nil)).Elem()
}

func (i *clonePtrType) ToClonePtrOutput() ClonePtrOutput {
	return i.ToClonePtrOutputWithContext(context.Background())
}

func (i *clonePtrType) ToClonePtrOutputWithContext(ctx context.Context) ClonePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClonePtrOutput)
}

type CloneOutput struct{ *pulumi.OutputState }

func (CloneOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Clone)(nil)).Elem()
}

func (o CloneOutput) ToCloneOutput() CloneOutput {
	return o
}

func (o CloneOutput) ToCloneOutputWithContext(ctx context.Context) CloneOutput {
	return o
}

func (o CloneOutput) ToClonePtrOutput() ClonePtrOutput {
	return o.ToClonePtrOutputWithContext(context.Background())
}

func (o CloneOutput) ToClonePtrOutputWithContext(ctx context.Context) ClonePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Clone) *Clone {
		return &v
	}).(ClonePtrOutput)
}

func (o CloneOutput) DataStoreId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Clone) *string { return v.DataStoreId }).(pulumi.StringPtrOutput)
}

func (o CloneOutput) FullClone() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Clone) *bool { return v.FullClone }).(pulumi.BoolPtrOutput)
}

func (o CloneOutput) Node() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Clone) *string { return v.Node }).(pulumi.StringPtrOutput)
}

func (o CloneOutput) Timeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Clone) *int { return v.Timeout }).(pulumi.IntPtrOutput)
}

func (o CloneOutput) VmId() pulumi.IntOutput {
	return o.ApplyT(func(v Clone) int { return v.VmId }).(pulumi.IntOutput)
}

type ClonePtrOutput struct{ *pulumi.OutputState }

func (ClonePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Clone)(nil)).Elem()
}

func (o ClonePtrOutput) ToClonePtrOutput() ClonePtrOutput {
	return o
}

func (o ClonePtrOutput) ToClonePtrOutputWithContext(ctx context.Context) ClonePtrOutput {
	return o
}

func (o ClonePtrOutput) Elem() CloneOutput {
	return o.ApplyT(func(v *Clone) Clone {
		if v != nil {
			return *v
		}
		var ret Clone
		return ret
	}).(CloneOutput)
}

func (o ClonePtrOutput) DataStoreId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Clone) *string {
		if v == nil {
			return nil
		}
		return v.DataStoreId
	}).(pulumi.StringPtrOutput)
}

func (o ClonePtrOutput) FullClone() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Clone) *bool {
		if v == nil {
			return nil
		}
		return v.FullClone
	}).(pulumi.BoolPtrOutput)
}

func (o ClonePtrOutput) Node() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Clone) *string {
		if v == nil {
			return nil
		}
		return v.Node
	}).(pulumi.StringPtrOutput)
}

func (o ClonePtrOutput) Timeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Clone) *int {
		if v == nil {
			return nil
		}
		return v.Timeout
	}).(pulumi.IntPtrOutput)
}

func (o ClonePtrOutput) VmId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Clone) *int {
		if v == nil {
			return nil
		}
		return &v.VmId
	}).(pulumi.IntPtrOutput)
}

type Cpu struct {
	Cores         *int       `pulumi:"cores"`
	FlagsDisabled []string   `pulumi:"flagsDisabled"`
	FlagsEnabled  []string   `pulumi:"flagsEnabled"`
	Hidden        *bool      `pulumi:"hidden"`
	HvVendorId    *string    `pulumi:"hvVendorId"`
	Limit         *float64   `pulumi:"limit"`
	Numa          *bool      `pulumi:"numa"`
	NumaNodes     []NumaNode `pulumi:"numaNodes"`
	PhysBits      *string    `pulumi:"physBits"`
	Sockets       *int       `pulumi:"sockets"`
	Type          *string    `pulumi:"type"`
	Units         *int       `pulumi:"units"`
	Vcpus         *int       `pulumi:"vcpus"`
}

// CpuInput is an input type that accepts CpuArgs and CpuOutput values.
// You can construct a concrete instance of `CpuInput` via:
//
//	CpuArgs{...}
type CpuInput interface {
	pulumi.Input

	ToCpuOutput() CpuOutput
	ToCpuOutputWithContext(context.Context) CpuOutput
}

type CpuArgs struct {
	Cores         pulumi.IntPtrInput      `pulumi:"cores"`
	FlagsDisabled pulumi.StringArrayInput `pulumi:"flagsDisabled"`
	FlagsEnabled  pulumi.StringArrayInput `pulumi:"flagsEnabled"`
	Hidden        pulumi.BoolPtrInput     `pulumi:"hidden"`
	HvVendorId    pulumi.StringPtrInput   `pulumi:"hvVendorId"`
	Limit         pulumi.Float64PtrInput  `pulumi:"limit"`
	Numa          pulumi.BoolPtrInput     `pulumi:"numa"`
	NumaNodes     NumaNodeArrayInput      `pulumi:"numaNodes"`
	PhysBits      pulumi.StringPtrInput   `pulumi:"physBits"`
	Sockets       pulumi.IntPtrInput      `pulumi:"sockets"`
	Type          pulumi.StringPtrInput   `pulumi:"type"`
	Units         pulumi.IntPtrInput      `pulumi:"units"`
	Vcpus         pulumi.IntPtrInput      `pulumi:"vcpus"`
}

func (CpuArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Cpu)(nil)).Elem()
}

func (i CpuArgs) ToCpuOutput() CpuOutput {
	return i.ToCpuOutputWithContext(context.Background())
}

func (i CpuArgs) ToCpuOutputWithContext(ctx context.Context) CpuOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CpuOutput)
}

func (i CpuArgs) ToCpuPtrOutput() CpuPtrOutput {
	return i.ToCpuPtrOutputWithContext(context.Background())
}

func (i CpuArgs) ToCpuPtrOutputWithContext(ctx context.Context) CpuPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CpuOutput).ToCpuPtrOutputWithContext(ctx)
}

// CpuPtrInput is an input type that accepts CpuArgs, CpuPtr and CpuPtrOutput values.
// You can construct a concrete instance of `CpuPtrInput` via:
//
//	        CpuArgs{...}
//
//	or:
//
//	        nil
type CpuPtrInput interface {
	pulumi.Input

	ToCpuPtrOutput() CpuPtrOutput
	ToCpuPtrOutputWithContext(context.Context) CpuPtrOutput
}

type cpuPtrType CpuArgs

func CpuPtr(v *CpuArgs) CpuPtrInput {
	return (*cpuPtrType)(v)
}

func (*cpuPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Cpu)(nil)).Elem()
}

func (i *cpuPtrType) ToCpuPtrOutput() CpuPtrOutput {
	return i.ToCpuPtrOutputWithContext(context.Background())
}

func (i *cpuPtrType) ToCpuPtrOutputWithContext(ctx context.Context) CpuPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CpuPtrOutput)
}

type CpuOutput struct{ *pulumi.OutputState }

func (CpuOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Cpu)(nil)).Elem()
}

func (o CpuOutput) ToCpuOutput() CpuOutput {
	return o
}

func (o CpuOutput) ToCpuOutputWithContext(ctx context.Context) CpuOutput {
	return o
}

func (o CpuOutput) ToCpuPtrOutput() CpuPtrOutput {
	return o.ToCpuPtrOutputWithContext(context.Background())
}

func (o CpuOutput) ToCpuPtrOutputWithContext(ctx context.Context) CpuPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Cpu) *Cpu {
		return &v
	}).(CpuPtrOutput)
}

func (o CpuOutput) Cores() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Cpu) *int { return v.Cores }).(pulumi.IntPtrOutput)
}

func (o CpuOutput) FlagsDisabled() pulumi.StringArrayOutput {
	return o.ApplyT(func(v Cpu) []string { return v.FlagsDisabled }).(pulumi.StringArrayOutput)
}

func (o CpuOutput) FlagsEnabled() pulumi.StringArrayOutput {
	return o.ApplyT(func(v Cpu) []string { return v.FlagsEnabled }).(pulumi.StringArrayOutput)
}

func (o CpuOutput) Hidden() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Cpu) *bool { return v.Hidden }).(pulumi.BoolPtrOutput)
}

func (o CpuOutput) HvVendorId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Cpu) *string { return v.HvVendorId }).(pulumi.StringPtrOutput)
}

func (o CpuOutput) Limit() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v Cpu) *float64 { return v.Limit }).(pulumi.Float64PtrOutput)
}

func (o CpuOutput) Numa() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Cpu) *bool { return v.Numa }).(pulumi.BoolPtrOutput)
}

func (o CpuOutput) NumaNodes() NumaNodeArrayOutput {
	return o.ApplyT(func(v Cpu) []NumaNode { return v.NumaNodes }).(NumaNodeArrayOutput)
}

func (o CpuOutput) PhysBits() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Cpu) *string { return v.PhysBits }).(pulumi.StringPtrOutput)
}

func (o CpuOutput) Sockets() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Cpu) *int { return v.Sockets }).(pulumi.IntPtrOutput)
}

func (o CpuOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Cpu) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o CpuOutput) Units() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Cpu) *int { return v.Units }).(pulumi.IntPtrOutput)
}

func (o CpuOutput) Vcpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Cpu) *int { return v.Vcpus }).(pulumi.IntPtrOutput)
}

type CpuPtrOutput struct{ *pulumi.OutputState }

func (CpuPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Cpu)(nil)).Elem()
}

func (o CpuPtrOutput) ToCpuPtrOutput() CpuPtrOutput {
	return o
}

func (o CpuPtrOutput) ToCpuPtrOutputWithContext(ctx context.Context) CpuPtrOutput {
	return o
}

func (o CpuPtrOutput) Elem() CpuOutput {
	return o.ApplyT(func(v *Cpu) Cpu {
		if v != nil {
			return *v
		}
		var ret Cpu
		return ret
	}).(CpuOutput)
}

func (o CpuPtrOutput) Cores() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Cpu) *int {
		if v == nil {
			return nil
		}
		return v.Cores
	}).(pulumi.IntPtrOutput)
}

func (o CpuPtrOutput) FlagsDisabled() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Cpu) []string {
		if v == nil {
			return nil
		}
		return v.FlagsDisabled
	}).(pulumi.StringArrayOutput)
}

func (o CpuPtrOutput) FlagsEnabled() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Cpu) []string {
		if v == nil {
			return nil
		}
		return v.FlagsEnabled
	}).(pulumi.StringArrayOutput)
}

func (o CpuPtrOutput) Hidden() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Cpu) *bool {
		if v == nil {
			return nil
		}
		return v.Hidden
	}).(pulumi.BoolPtrOutput)
}

func (o CpuPtrOutput) HvVendorId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Cpu) *string {
		if v == nil {
			return nil
		}
		return v.HvVendorId
	}).(pulumi.StringPtrOutput)
}

func (o CpuPtrOutput) Limit() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *Cpu) *float64 {
		if v == nil {
			return nil
		}
		return v.Limit
	}).(pulumi.Float64PtrOutput)
}

func (o CpuPtrOutput) Numa() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Cpu) *bool {
		if v == nil {
			return nil
		}
		return v.Numa
	}).(pulumi.BoolPtrOutput)
}

func (o CpuPtrOutput) NumaNodes() NumaNodeArrayOutput {
	return o.ApplyT(func(v *Cpu) []NumaNode {
		if v == nil {
			return nil
		}
		return v.NumaNodes
	}).(NumaNodeArrayOutput)
}

func (o CpuPtrOutput) PhysBits() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Cpu) *string {
		if v == nil {
			return nil
		}
		return v.PhysBits
	}).(pulumi.StringPtrOutput)
}

func (o CpuPtrOutput) Sockets() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Cpu) *int {
		if v == nil {
			return nil
		}
		return v.Sockets
	}).(pulumi.IntPtrOutput)
}

func (o CpuPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Cpu) *string {
		if v == nil {
			return nil
		}
		return v.Type
	}).(pulumi.StringPtrOutput)
}

func (o CpuPtrOutput) Units() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Cpu) *int {
		if v == nil {
			return nil
		}
		return v.Units
	}).(pulumi.IntPtrOutput)
}

func (o CpuPtrOutput) Vcpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Cpu) *int {
		if v == nil {
			return nil
		}
		return v.Vcpus
	}).(pulumi.IntPtrOutput)
}

type Disk struct {
	Filename  *string `pulumi:"filename"`
	Interface string  `pulumi:"interface"`
	Size      int     `pulumi:"size"`
	Storage   string  `pulumi:"storage"`
}

// DiskInput is an input type that accepts DiskArgs and DiskOutput values.
// You can construct a concrete instance of `DiskInput` via:
//
//	DiskArgs{...}
type DiskInput interface {
	pulumi.Input

	ToDiskOutput() DiskOutput
	ToDiskOutputWithContext(context.Context) DiskOutput
}

type DiskArgs struct {
	Filename  pulumi.StringPtrInput `pulumi:"filename"`
	Interface pulumi.StringInput    `pulumi:"interface"`
	Size      pulumi.IntInput       `pulumi:"size"`
	Storage   pulumi.StringInput    `pulumi:"storage"`
}

func (DiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Disk)(nil)).Elem()
}

func (i DiskArgs) ToDiskOutput() DiskOutput {
	return i.ToDiskOutputWithContext(context.Background())
}

func (i DiskArgs) ToDiskOutputWithContext(ctx context.Context) DiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DiskOutput)
}

// DiskArrayInput is an input type that accepts DiskArray and DiskArrayOutput values.
// You can construct a concrete instance of `DiskArrayInput` via:
//
//	DiskArray{ DiskArgs{...} }
type DiskArrayInput interface {
	pulumi.Input

	ToDiskArrayOutput() DiskArrayOutput
	ToDiskArrayOutputWithContext(context.Context) DiskArrayOutput
}

type DiskArray []DiskInput

func (DiskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Disk)(nil)).Elem()
}

func (i DiskArray) ToDiskArrayOutput() DiskArrayOutput {
	return i.ToDiskArrayOutputWithContext(context.Background())
}

func (i DiskArray) ToDiskArrayOutputWithContext(ctx context.Context) DiskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DiskArrayOutput)
}

type DiskOutput struct{ *pulumi.OutputState }

func (DiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Disk)(nil)).Elem()
}

func (o DiskOutput) ToDiskOutput() DiskOutput {
	return o
}

func (o DiskOutput) ToDiskOutputWithContext(ctx context.Context) DiskOutput {
	return o
}

func (o DiskOutput) Filename() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Disk) *string { return v.Filename }).(pulumi.StringPtrOutput)
}

func (o DiskOutput) Interface() pulumi.StringOutput {
	return o.ApplyT(func(v Disk) string { return v.Interface }).(pulumi.StringOutput)
}

func (o DiskOutput) Size() pulumi.IntOutput {
	return o.ApplyT(func(v Disk) int { return v.Size }).(pulumi.IntOutput)
}

func (o DiskOutput) Storage() pulumi.StringOutput {
	return o.ApplyT(func(v Disk) string { return v.Storage }).(pulumi.StringOutput)
}

type DiskArrayOutput struct{ *pulumi.OutputState }

func (DiskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Disk)(nil)).Elem()
}

func (o DiskArrayOutput) ToDiskArrayOutput() DiskArrayOutput {
	return o
}

func (o DiskArrayOutput) ToDiskArrayOutputWithContext(ctx context.Context) DiskArrayOutput {
	return o
}

func (o DiskArrayOutput) Index(i pulumi.IntInput) DiskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Disk {
		return vs[0].([]Disk)[vs[1].(int)]
	}).(DiskOutput)
}

type NumaNode struct {
	Cpus      string  `pulumi:"cpus"`
	HostNodes *string `pulumi:"hostNodes"`
	Memory    *int    `pulumi:"memory"`
	Policy    *string `pulumi:"policy"`
}

// NumaNodeInput is an input type that accepts NumaNodeArgs and NumaNodeOutput values.
// You can construct a concrete instance of `NumaNodeInput` via:
//
//	NumaNodeArgs{...}
type NumaNodeInput interface {
	pulumi.Input

	ToNumaNodeOutput() NumaNodeOutput
	ToNumaNodeOutputWithContext(context.Context) NumaNodeOutput
}

type NumaNodeArgs struct {
	Cpus      pulumi.StringInput    `pulumi:"cpus"`
	HostNodes pulumi.StringPtrInput `pulumi:"hostNodes"`
	Memory    pulumi.IntPtrInput    `pulumi:"memory"`
	Policy    pulumi.StringPtrInput `pulumi:"policy"`
}

func (NumaNodeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NumaNode)(nil)).Elem()
}

func (i NumaNodeArgs) ToNumaNodeOutput() NumaNodeOutput {
	return i.ToNumaNodeOutputWithContext(context.Background())
}

func (i NumaNodeArgs) ToNumaNodeOutputWithContext(ctx context.Context) NumaNodeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NumaNodeOutput)
}

// NumaNodeArrayInput is an input type that accepts NumaNodeArray and NumaNodeArrayOutput values.
// You can construct a concrete instance of `NumaNodeArrayInput` via:
//
//	NumaNodeArray{ NumaNodeArgs{...} }
type NumaNodeArrayInput interface {
	pulumi.Input

	ToNumaNodeArrayOutput() NumaNodeArrayOutput
	ToNumaNodeArrayOutputWithContext(context.Context) NumaNodeArrayOutput
}

type NumaNodeArray []NumaNodeInput

func (NumaNodeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NumaNode)(nil)).Elem()
}

func (i NumaNodeArray) ToNumaNodeArrayOutput() NumaNodeArrayOutput {
	return i.ToNumaNodeArrayOutputWithContext(context.Background())
}

func (i NumaNodeArray) ToNumaNodeArrayOutputWithContext(ctx context.Context) NumaNodeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NumaNodeArrayOutput)
}

type NumaNodeOutput struct{ *pulumi.OutputState }

func (NumaNodeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NumaNode)(nil)).Elem()
}

func (o NumaNodeOutput) ToNumaNodeOutput() NumaNodeOutput {
	return o
}

func (o NumaNodeOutput) ToNumaNodeOutputWithContext(ctx context.Context) NumaNodeOutput {
	return o
}

func (o NumaNodeOutput) Cpus() pulumi.StringOutput {
	return o.ApplyT(func(v NumaNode) string { return v.Cpus }).(pulumi.StringOutput)
}

func (o NumaNodeOutput) HostNodes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v NumaNode) *string { return v.HostNodes }).(pulumi.StringPtrOutput)
}

func (o NumaNodeOutput) Memory() pulumi.IntPtrOutput {
	return o.ApplyT(func(v NumaNode) *int { return v.Memory }).(pulumi.IntPtrOutput)
}

func (o NumaNodeOutput) Policy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v NumaNode) *string { return v.Policy }).(pulumi.StringPtrOutput)
}

type NumaNodeArrayOutput struct{ *pulumi.OutputState }

func (NumaNodeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NumaNode)(nil)).Elem()
}

func (o NumaNodeArrayOutput) ToNumaNodeArrayOutput() NumaNodeArrayOutput {
	return o
}

func (o NumaNodeArrayOutput) ToNumaNodeArrayOutputWithContext(ctx context.Context) NumaNodeArrayOutput {
	return o
}

func (o NumaNodeArrayOutput) Index(i pulumi.IntInput) NumaNodeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NumaNode {
		return vs[0].([]NumaNode)[vs[1].(int)]
	}).(NumaNodeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloneInput)(nil)).Elem(), CloneArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClonePtrInput)(nil)).Elem(), CloneArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CpuInput)(nil)).Elem(), CpuArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CpuPtrInput)(nil)).Elem(), CpuArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DiskInput)(nil)).Elem(), DiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DiskArrayInput)(nil)).Elem(), DiskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NumaNodeInput)(nil)).Elem(), NumaNodeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NumaNodeArrayInput)(nil)).Elem(), NumaNodeArray{})
	pulumi.RegisterOutputType(CloneOutput{})
	pulumi.RegisterOutputType(ClonePtrOutput{})
	pulumi.RegisterOutputType(CpuOutput{})
	pulumi.RegisterOutputType(CpuPtrOutput{})
	pulumi.RegisterOutputType(DiskOutput{})
	pulumi.RegisterOutputType(DiskArrayOutput{})
	pulumi.RegisterOutputType(NumaNodeOutput{})
	pulumi.RegisterOutputType(NumaNodeArrayOutput{})
}
