// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve.sdnapply;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SDNApplyArgs extends com.pulumi.resources.ResourceArgs {

    public static final SDNApplyArgs Empty = new SDNApplyArgs();

    /**
     * Arbitrary key-value pairs that can include resource outputs or complex objects. When any trigger value changes, the SDN apply is re-executed.
     * 
     */
    @Import(name="triggers")
    private @Nullable Output<Map<String,Object>> triggers;

    /**
     * @return Arbitrary key-value pairs that can include resource outputs or complex objects. When any trigger value changes, the SDN apply is re-executed.
     * 
     */
    public Optional<Output<Map<String,Object>>> triggers() {
        return Optional.ofNullable(this.triggers);
    }

    private SDNApplyArgs() {}

    private SDNApplyArgs(SDNApplyArgs $) {
        this.triggers = $.triggers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SDNApplyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SDNApplyArgs $;

        public Builder() {
            $ = new SDNApplyArgs();
        }

        public Builder(SDNApplyArgs defaults) {
            $ = new SDNApplyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param triggers Arbitrary key-value pairs that can include resource outputs or complex objects. When any trigger value changes, the SDN apply is re-executed.
         * 
         * @return builder
         * 
         */
        public Builder triggers(@Nullable Output<Map<String,Object>> triggers) {
            $.triggers = triggers;
            return this;
        }

        /**
         * @param triggers Arbitrary key-value pairs that can include resource outputs or complex objects. When any trigger value changes, the SDN apply is re-executed.
         * 
         * @return builder
         * 
         */
        public Builder triggers(Map<String,Object> triggers) {
            return triggers(Output.of(triggers));
        }

        public SDNApplyArgs build() {
            return $;
        }
    }

}
