// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve.vm;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.hctamu.pve.proxmox.inputs.CPUArgs;
import io.github.hctamu.pve.proxmox.inputs.CloneArgs;
import io.github.hctamu.pve.proxmox.inputs.DiskArgs;
import io.github.hctamu.pve.proxmox.inputs.EfiDiskArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VMArgs extends com.pulumi.resources.ResourceArgs {

    public static final VMArgs Empty = new VMArgs();

    /**
     * Automatically start the VM when the host boots (1 to enable, 0 to disable).
     * 
     */
    @Import(name="autostart")
    private @Nullable Output<Integer> autostart;

    /**
     * @return Automatically start the VM when the host boots (1 to enable, 0 to disable).
     * 
     */
    public Optional<Output<Integer>> autostart() {
        return Optional.ofNullable(this.autostart);
    }

    /**
     * Minimum memory for ballooning in megabytes (0 disables the balloon device).
     * 
     */
    @Import(name="balloon")
    private @Nullable Output<Integer> balloon;

    /**
     * @return Minimum memory for ballooning in megabytes (0 disables the balloon device).
     * 
     */
    public Optional<Output<Integer>> balloon() {
        return Optional.ofNullable(this.balloon);
    }

    /**
     * Clone configuration for creating the VM from a source template or VM.
     * 
     */
    @Import(name="clone")
    private @Nullable Output<CloneArgs> clone;

    /**
     * @return Clone configuration for creating the VM from a source template or VM.
     * 
     */
    public Optional<Output<CloneArgs>> clone_() {
        return Optional.ofNullable(this.clone);
    }

    /**
     * CPU configuration including type, topology, and feature flags.
     * 
     */
    @Import(name="cpu")
    private @Nullable Output<CPUArgs> cpu;

    /**
     * @return CPU configuration including type, topology, and feature flags.
     * 
     */
    public Optional<Output<CPUArgs>> cpu() {
        return Optional.ofNullable(this.cpu);
    }

    /**
     * Description or notes for the virtual machine.
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return Description or notes for the virtual machine.
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * List of disk configurations attached to the virtual machine.
     * 
     */
    @Import(name="disks", required=true)
    private Output<List<DiskArgs>> disks;

    /**
     * @return List of disk configurations attached to the virtual machine.
     * 
     */
    public Output<List<DiskArgs>> disks() {
        return this.disks;
    }

    /**
     * EFI disk configuration (required when bios is set to ovmf).
     * 
     */
    @Import(name="efidisk")
    private @Nullable Output<EfiDiskArgs> efidisk;

    /**
     * @return EFI disk configuration (required when bios is set to ovmf).
     * 
     */
    public Optional<Output<EfiDiskArgs>> efidisk() {
        return Optional.ofNullable(this.efidisk);
    }

    /**
     * Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
     * 
     */
    @Import(name="hotplug")
    private @Nullable Output<String> hotplug;

    /**
     * @return Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
     * 
     */
    public Optional<Output<String>> hotplug() {
        return Optional.ofNullable(this.hotplug);
    }

    /**
     * Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
     * 
     */
    @Import(name="machine")
    private @Nullable Output<String> machine;

    /**
     * @return Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
     * 
     */
    public Optional<Output<String>> machine() {
        return Optional.ofNullable(this.machine);
    }

    /**
     * Memory size in megabytes.
     * 
     */
    @Import(name="memory")
    private @Nullable Output<Integer> memory;

    /**
     * @return Memory size in megabytes.
     * 
     */
    public Optional<Output<Integer>> memory() {
        return Optional.ofNullable(this.memory);
    }

    /**
     * Name of the virtual machine.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Name of the virtual machine.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Proxmox node where the VM resides.
     * 
     */
    @Import(name="node")
    private @Nullable Output<String> node;

    /**
     * @return Proxmox node where the VM resides.
     * 
     */
    public Optional<Output<String>> node() {
        return Optional.ofNullable(this.node);
    }

    /**
     * Guest operating system type (e.g., l26, win11, other).
     * 
     */
    @Import(name="ostype")
    private @Nullable Output<String> ostype;

    /**
     * @return Guest operating system type (e.g., l26, win11, other).
     * 
     */
    public Optional<Output<String>> ostype() {
        return Optional.ofNullable(this.ostype);
    }

    /**
     * Tags associated with the virtual machine.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<List<String>> tags;

    /**
     * @return Tags associated with the virtual machine.
     * 
     */
    public Optional<Output<List<String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    /**
     * Mark the VM as a template (1) or a regular VM (0).
     * 
     */
    @Import(name="template")
    private @Nullable Output<Integer> template;

    /**
     * @return Mark the VM as a template (1) or a regular VM (0).
     * 
     */
    public Optional<Output<Integer>> template() {
        return Optional.ofNullable(this.template);
    }

    /**
     * Unique numeric identifier for the virtual machine (auto-assigned if omitted).
     * 
     */
    @Import(name="vmId")
    private @Nullable Output<Integer> vmId;

    /**
     * @return Unique numeric identifier for the virtual machine (auto-assigned if omitted).
     * 
     */
    public Optional<Output<Integer>> vmId() {
        return Optional.ofNullable(this.vmId);
    }

    private VMArgs() {}

    private VMArgs(VMArgs $) {
        this.autostart = $.autostart;
        this.balloon = $.balloon;
        this.clone = $.clone;
        this.cpu = $.cpu;
        this.description = $.description;
        this.disks = $.disks;
        this.efidisk = $.efidisk;
        this.hotplug = $.hotplug;
        this.machine = $.machine;
        this.memory = $.memory;
        this.name = $.name;
        this.node = $.node;
        this.ostype = $.ostype;
        this.tags = $.tags;
        this.template = $.template;
        this.vmId = $.vmId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VMArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VMArgs $;

        public Builder() {
            $ = new VMArgs();
        }

        public Builder(VMArgs defaults) {
            $ = new VMArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param autostart Automatically start the VM when the host boots (1 to enable, 0 to disable).
         * 
         * @return builder
         * 
         */
        public Builder autostart(@Nullable Output<Integer> autostart) {
            $.autostart = autostart;
            return this;
        }

        /**
         * @param autostart Automatically start the VM when the host boots (1 to enable, 0 to disable).
         * 
         * @return builder
         * 
         */
        public Builder autostart(Integer autostart) {
            return autostart(Output.of(autostart));
        }

        /**
         * @param balloon Minimum memory for ballooning in megabytes (0 disables the balloon device).
         * 
         * @return builder
         * 
         */
        public Builder balloon(@Nullable Output<Integer> balloon) {
            $.balloon = balloon;
            return this;
        }

        /**
         * @param balloon Minimum memory for ballooning in megabytes (0 disables the balloon device).
         * 
         * @return builder
         * 
         */
        public Builder balloon(Integer balloon) {
            return balloon(Output.of(balloon));
        }

        /**
         * @param clone Clone configuration for creating the VM from a source template or VM.
         * 
         * @return builder
         * 
         */
        public Builder clone_(@Nullable Output<CloneArgs> clone) {
            $.clone = clone;
            return this;
        }

        /**
         * @param clone Clone configuration for creating the VM from a source template or VM.
         * 
         * @return builder
         * 
         */
        public Builder clone_(CloneArgs clone) {
            return clone_(Output.of(clone));
        }

        /**
         * @param cpu CPU configuration including type, topology, and feature flags.
         * 
         * @return builder
         * 
         */
        public Builder cpu(@Nullable Output<CPUArgs> cpu) {
            $.cpu = cpu;
            return this;
        }

        /**
         * @param cpu CPU configuration including type, topology, and feature flags.
         * 
         * @return builder
         * 
         */
        public Builder cpu(CPUArgs cpu) {
            return cpu(Output.of(cpu));
        }

        /**
         * @param description Description or notes for the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description Description or notes for the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param disks List of disk configurations attached to the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder disks(Output<List<DiskArgs>> disks) {
            $.disks = disks;
            return this;
        }

        /**
         * @param disks List of disk configurations attached to the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder disks(List<DiskArgs> disks) {
            return disks(Output.of(disks));
        }

        /**
         * @param disks List of disk configurations attached to the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder disks(DiskArgs... disks) {
            return disks(List.of(disks));
        }

        /**
         * @param efidisk EFI disk configuration (required when bios is set to ovmf).
         * 
         * @return builder
         * 
         */
        public Builder efidisk(@Nullable Output<EfiDiskArgs> efidisk) {
            $.efidisk = efidisk;
            return this;
        }

        /**
         * @param efidisk EFI disk configuration (required when bios is set to ovmf).
         * 
         * @return builder
         * 
         */
        public Builder efidisk(EfiDiskArgs efidisk) {
            return efidisk(Output.of(efidisk));
        }

        /**
         * @param hotplug Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
         * 
         * @return builder
         * 
         */
        public Builder hotplug(@Nullable Output<String> hotplug) {
            $.hotplug = hotplug;
            return this;
        }

        /**
         * @param hotplug Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
         * 
         * @return builder
         * 
         */
        public Builder hotplug(String hotplug) {
            return hotplug(Output.of(hotplug));
        }

        /**
         * @param machine Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
         * 
         * @return builder
         * 
         */
        public Builder machine(@Nullable Output<String> machine) {
            $.machine = machine;
            return this;
        }

        /**
         * @param machine Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
         * 
         * @return builder
         * 
         */
        public Builder machine(String machine) {
            return machine(Output.of(machine));
        }

        /**
         * @param memory Memory size in megabytes.
         * 
         * @return builder
         * 
         */
        public Builder memory(@Nullable Output<Integer> memory) {
            $.memory = memory;
            return this;
        }

        /**
         * @param memory Memory size in megabytes.
         * 
         * @return builder
         * 
         */
        public Builder memory(Integer memory) {
            return memory(Output.of(memory));
        }

        /**
         * @param name Name of the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param node Proxmox node where the VM resides.
         * 
         * @return builder
         * 
         */
        public Builder node(@Nullable Output<String> node) {
            $.node = node;
            return this;
        }

        /**
         * @param node Proxmox node where the VM resides.
         * 
         * @return builder
         * 
         */
        public Builder node(String node) {
            return node(Output.of(node));
        }

        /**
         * @param ostype Guest operating system type (e.g., l26, win11, other).
         * 
         * @return builder
         * 
         */
        public Builder ostype(@Nullable Output<String> ostype) {
            $.ostype = ostype;
            return this;
        }

        /**
         * @param ostype Guest operating system type (e.g., l26, win11, other).
         * 
         * @return builder
         * 
         */
        public Builder ostype(String ostype) {
            return ostype(Output.of(ostype));
        }

        /**
         * @param tags Tags associated with the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<List<String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags Tags associated with the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder tags(List<String> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param tags Tags associated with the virtual machine.
         * 
         * @return builder
         * 
         */
        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }

        /**
         * @param template Mark the VM as a template (1) or a regular VM (0).
         * 
         * @return builder
         * 
         */
        public Builder template(@Nullable Output<Integer> template) {
            $.template = template;
            return this;
        }

        /**
         * @param template Mark the VM as a template (1) or a regular VM (0).
         * 
         * @return builder
         * 
         */
        public Builder template(Integer template) {
            return template(Output.of(template));
        }

        /**
         * @param vmId Unique numeric identifier for the virtual machine (auto-assigned if omitted).
         * 
         * @return builder
         * 
         */
        public Builder vmId(@Nullable Output<Integer> vmId) {
            $.vmId = vmId;
            return this;
        }

        /**
         * @param vmId Unique numeric identifier for the virtual machine (auto-assigned if omitted).
         * 
         * @return builder
         * 
         */
        public Builder vmId(Integer vmId) {
            return vmId(Output.of(vmId));
        }

        public VMArgs build() {
            if ($.disks == null) {
                throw new MissingRequiredPropertyException("VMArgs", "disks");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("VMArgs", "name");
            }
            return $;
        }
    }

}
