// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.Proxmox.Outputs
{

    /// <summary>
    /// Disk configuration for the virtual machine.
    /// </summary>
    [OutputType]
    public sealed class Disk
    {
        /// <summary>
        /// File name of the disk image (computed by Proxmox if not provided).
        /// </summary>
        public readonly string? Filename;
        /// <summary>
        /// Disk interface type and slot (e.g., scsi0, virtio0, ide1, sata2).
        /// </summary>
        public readonly string Interface;
        /// <summary>
        /// Disk size in gigabytes.
        /// </summary>
        public readonly int Size;
        /// <summary>
        /// Target storage pool for the disk (e.g., local-lvm, ceph-pool).
        /// </summary>
        public readonly string Storage;

        [OutputConstructor]
        private Disk(
            string? filename,

            string @interface,

            int size,

            string storage)
        {
            Filename = filename;
            Interface = @interface;
            Size = size;
            Storage = storage;
        }
    }
}
