// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve.vm.outputs;

import com.pulumi.core.annotations.CustomType;
import io.github.hctamu.pve.vm.outputs.NumaNode;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class Cpu {
    private @Nullable Integer cores;
    private @Nullable List<String> flagsDisabled;
    private @Nullable List<String> flagsEnabled;
    private @Nullable Boolean hidden;
    private @Nullable String hvVendorId;
    private @Nullable Double limit;
    private @Nullable Boolean numa;
    private @Nullable List<NumaNode> numaNodes;
    private @Nullable String physBits;
    private @Nullable Integer sockets;
    private @Nullable String type;
    private @Nullable Integer units;
    private @Nullable Integer vcpus;

    private Cpu() {}
    public Optional<Integer> cores() {
        return Optional.ofNullable(this.cores);
    }
    public List<String> flagsDisabled() {
        return this.flagsDisabled == null ? List.of() : this.flagsDisabled;
    }
    public List<String> flagsEnabled() {
        return this.flagsEnabled == null ? List.of() : this.flagsEnabled;
    }
    public Optional<Boolean> hidden() {
        return Optional.ofNullable(this.hidden);
    }
    public Optional<String> hvVendorId() {
        return Optional.ofNullable(this.hvVendorId);
    }
    public Optional<Double> limit() {
        return Optional.ofNullable(this.limit);
    }
    public Optional<Boolean> numa() {
        return Optional.ofNullable(this.numa);
    }
    public List<NumaNode> numaNodes() {
        return this.numaNodes == null ? List.of() : this.numaNodes;
    }
    public Optional<String> physBits() {
        return Optional.ofNullable(this.physBits);
    }
    public Optional<Integer> sockets() {
        return Optional.ofNullable(this.sockets);
    }
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }
    public Optional<Integer> units() {
        return Optional.ofNullable(this.units);
    }
    public Optional<Integer> vcpus() {
        return Optional.ofNullable(this.vcpus);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Cpu defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer cores;
        private @Nullable List<String> flagsDisabled;
        private @Nullable List<String> flagsEnabled;
        private @Nullable Boolean hidden;
        private @Nullable String hvVendorId;
        private @Nullable Double limit;
        private @Nullable Boolean numa;
        private @Nullable List<NumaNode> numaNodes;
        private @Nullable String physBits;
        private @Nullable Integer sockets;
        private @Nullable String type;
        private @Nullable Integer units;
        private @Nullable Integer vcpus;
        public Builder() {}
        public Builder(Cpu defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cores = defaults.cores;
    	      this.flagsDisabled = defaults.flagsDisabled;
    	      this.flagsEnabled = defaults.flagsEnabled;
    	      this.hidden = defaults.hidden;
    	      this.hvVendorId = defaults.hvVendorId;
    	      this.limit = defaults.limit;
    	      this.numa = defaults.numa;
    	      this.numaNodes = defaults.numaNodes;
    	      this.physBits = defaults.physBits;
    	      this.sockets = defaults.sockets;
    	      this.type = defaults.type;
    	      this.units = defaults.units;
    	      this.vcpus = defaults.vcpus;
        }

        @CustomType.Setter
        public Builder cores(@Nullable Integer cores) {

            this.cores = cores;
            return this;
        }
        @CustomType.Setter
        public Builder flagsDisabled(@Nullable List<String> flagsDisabled) {

            this.flagsDisabled = flagsDisabled;
            return this;
        }
        public Builder flagsDisabled(String... flagsDisabled) {
            return flagsDisabled(List.of(flagsDisabled));
        }
        @CustomType.Setter
        public Builder flagsEnabled(@Nullable List<String> flagsEnabled) {

            this.flagsEnabled = flagsEnabled;
            return this;
        }
        public Builder flagsEnabled(String... flagsEnabled) {
            return flagsEnabled(List.of(flagsEnabled));
        }
        @CustomType.Setter
        public Builder hidden(@Nullable Boolean hidden) {

            this.hidden = hidden;
            return this;
        }
        @CustomType.Setter
        public Builder hvVendorId(@Nullable String hvVendorId) {

            this.hvVendorId = hvVendorId;
            return this;
        }
        @CustomType.Setter
        public Builder limit(@Nullable Double limit) {

            this.limit = limit;
            return this;
        }
        @CustomType.Setter
        public Builder numa(@Nullable Boolean numa) {

            this.numa = numa;
            return this;
        }
        @CustomType.Setter
        public Builder numaNodes(@Nullable List<NumaNode> numaNodes) {

            this.numaNodes = numaNodes;
            return this;
        }
        public Builder numaNodes(NumaNode... numaNodes) {
            return numaNodes(List.of(numaNodes));
        }
        @CustomType.Setter
        public Builder physBits(@Nullable String physBits) {

            this.physBits = physBits;
            return this;
        }
        @CustomType.Setter
        public Builder sockets(@Nullable Integer sockets) {

            this.sockets = sockets;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder units(@Nullable Integer units) {

            this.units = units;
            return this;
        }
        @CustomType.Setter
        public Builder vcpus(@Nullable Integer vcpus) {

            this.vcpus = vcpus;
            return this;
        }
        public Cpu build() {
            final var _resultValue = new Cpu();
            _resultValue.cores = cores;
            _resultValue.flagsDisabled = flagsDisabled;
            _resultValue.flagsEnabled = flagsEnabled;
            _resultValue.hidden = hidden;
            _resultValue.hvVendorId = hvVendorId;
            _resultValue.limit = limit;
            _resultValue.numa = numa;
            _resultValue.numaNodes = numaNodes;
            _resultValue.physBits = physBits;
            _resultValue.sockets = sockets;
            _resultValue.type = type;
            _resultValue.units = units;
            _resultValue.vcpus = vcpus;
            return _resultValue;
        }
    }
}
