// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve.vm.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class EfiDisk {
    private String efitype;
    private @Nullable String filename;
    private @Nullable Boolean preEnrolledKeys;
    private String storage;

    private EfiDisk() {}
    public String efitype() {
        return this.efitype;
    }
    public Optional<String> filename() {
        return Optional.ofNullable(this.filename);
    }
    public Optional<Boolean> preEnrolledKeys() {
        return Optional.ofNullable(this.preEnrolledKeys);
    }
    public String storage() {
        return this.storage;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EfiDisk defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String efitype;
        private @Nullable String filename;
        private @Nullable Boolean preEnrolledKeys;
        private String storage;
        public Builder() {}
        public Builder(EfiDisk defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.efitype = defaults.efitype;
    	      this.filename = defaults.filename;
    	      this.preEnrolledKeys = defaults.preEnrolledKeys;
    	      this.storage = defaults.storage;
        }

        @CustomType.Setter
        public Builder efitype(String efitype) {
            if (efitype == null) {
              throw new MissingRequiredPropertyException("EfiDisk", "efitype");
            }
            this.efitype = efitype;
            return this;
        }
        @CustomType.Setter
        public Builder filename(@Nullable String filename) {

            this.filename = filename;
            return this;
        }
        @CustomType.Setter
        public Builder preEnrolledKeys(@Nullable Boolean preEnrolledKeys) {

            this.preEnrolledKeys = preEnrolledKeys;
            return this;
        }
        @CustomType.Setter
        public Builder storage(String storage) {
            if (storage == null) {
              throw new MissingRequiredPropertyException("EfiDisk", "storage");
            }
            this.storage = storage;
            return this;
        }
        public EfiDisk build() {
            final var _resultValue = new EfiDisk();
            _resultValue.efitype = efitype;
            _resultValue.filename = filename;
            _resultValue.preEnrolledKeys = preEnrolledKeys;
            _resultValue.storage = storage;
            return _resultValue;
        }
    }
}
