// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.Proxmox.Inputs
{

    /// <summary>
    /// EFI disk configuration for the virtual machine.
    /// </summary>
    public sealed class EfiDiskArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// EFI firmware size: '2m' (2 MB, legacy) or '4m' (4 MB, supports Secure Boot).
        /// </summary>
        [Input("efitype", required: true)]
        public Input<string> Efitype { get; set; } = null!;

        /// <summary>
        /// File name of the EFI disk image (computed by Proxmox if not provided).
        /// </summary>
        [Input("filename")]
        public Input<string>? Filename { get; set; }

        /// <summary>
        /// Pre-enroll Microsoft and standard UEFI keys into the EFI firmware.
        /// </summary>
        [Input("preEnrolledKeys")]
        public Input<bool>? PreEnrolledKeys { get; set; }

        /// <summary>
        /// Target storage pool for the EFI disk (e.g., local-lvm).
        /// </summary>
        [Input("storage", required: true)]
        public Input<string> Storage { get; set; } = null!;

        public EfiDiskArgs()
        {
        }
        public static new EfiDiskArgs Empty => new EfiDiskArgs();
    }
}
