// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package proxmox

import (
	"context"
	"reflect"

	"github.com/hctamu/pulumi-pve/sdk/go/pve/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

// CPU configuration for the virtual machine.
type CPU struct {
	// Number of CPU cores per socket.
	Cores *int `pulumi:"cores"`
	// List of CPU flags to disable.
	FlagsDisabled []string `pulumi:"flagsDisabled"`
	// List of CPU flags to enable (e.g., pcid, spec-ctrl).
	FlagsEnabled []string `pulumi:"flagsEnabled"`
	// Hide VM CPU type from the guest operating system.
	Hidden *bool `pulumi:"hidden"`
	// Hyper-V vendor ID presented to the guest (up to 12 characters).
	HvVendorId *string `pulumi:"hvVendorId"`
	// CPU usage limit as a fraction of one core (e.g., 1.5 caps at 150%).
	Limit *float64 `pulumi:"limit"`
	// Enable NUMA topology.
	Numa *bool `pulumi:"numa"`
	// NUMA node topology configuration.
	NumaNodes []NumaNode `pulumi:"numaNodes"`
	// Number of physical address bits exposed to the guest (e.g., 36, 40, 48).
	PhysBits *string `pulumi:"physBits"`
	// Number of CPU sockets.
	Sockets *int `pulumi:"sockets"`
	// CPU type (e.g., host, kvm64, x86-64-v2-AES).
	Type *string `pulumi:"type"`
	// CPU weight for the scheduler relative to other VMs (higher = more CPU time).
	Units *int `pulumi:"units"`
	// Number of hotplugged vCPUs (must be <= cores * sockets).
	Vcpus *int `pulumi:"vcpus"`
}

// Defaults sets the appropriate defaults for CPU
func (val *CPU) Defaults() *CPU {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Cores == nil {
		if d := internal.GetEnvOrDefault(1, internal.ParseEnvInt, "Number of CPU cores"); d != nil {
			cores_ := d.(int)
			tmp.Cores = &cores_
		}
	}
	return &tmp
}

// CPUInput is an input type that accepts CPUArgs and CPUOutput values.
// You can construct a concrete instance of `CPUInput` via:
//
//	CPUArgs{...}
type CPUInput interface {
	pulumi.Input

	ToCPUOutput() CPUOutput
	ToCPUOutputWithContext(context.Context) CPUOutput
}

// CPU configuration for the virtual machine.
type CPUArgs struct {
	// Number of CPU cores per socket.
	Cores pulumi.IntPtrInput `pulumi:"cores"`
	// List of CPU flags to disable.
	FlagsDisabled pulumi.StringArrayInput `pulumi:"flagsDisabled"`
	// List of CPU flags to enable (e.g., pcid, spec-ctrl).
	FlagsEnabled pulumi.StringArrayInput `pulumi:"flagsEnabled"`
	// Hide VM CPU type from the guest operating system.
	Hidden pulumi.BoolPtrInput `pulumi:"hidden"`
	// Hyper-V vendor ID presented to the guest (up to 12 characters).
	HvVendorId pulumi.StringPtrInput `pulumi:"hvVendorId"`
	// CPU usage limit as a fraction of one core (e.g., 1.5 caps at 150%).
	Limit pulumi.Float64PtrInput `pulumi:"limit"`
	// Enable NUMA topology.
	Numa pulumi.BoolPtrInput `pulumi:"numa"`
	// NUMA node topology configuration.
	NumaNodes NumaNodeArrayInput `pulumi:"numaNodes"`
	// Number of physical address bits exposed to the guest (e.g., 36, 40, 48).
	PhysBits pulumi.StringPtrInput `pulumi:"physBits"`
	// Number of CPU sockets.
	Sockets pulumi.IntPtrInput `pulumi:"sockets"`
	// CPU type (e.g., host, kvm64, x86-64-v2-AES).
	Type pulumi.StringPtrInput `pulumi:"type"`
	// CPU weight for the scheduler relative to other VMs (higher = more CPU time).
	Units pulumi.IntPtrInput `pulumi:"units"`
	// Number of hotplugged vCPUs (must be <= cores * sockets).
	Vcpus pulumi.IntPtrInput `pulumi:"vcpus"`
}

// Defaults sets the appropriate defaults for CPUArgs
func (val *CPUArgs) Defaults() *CPUArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Cores == nil {
		if d := internal.GetEnvOrDefault(1, internal.ParseEnvInt, "Number of CPU cores"); d != nil {
			tmp.Cores = pulumi.IntPtr(d.(int))
		}
	}
	return &tmp
}
func (CPUArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*CPU)(nil)).Elem()
}

func (i CPUArgs) ToCPUOutput() CPUOutput {
	return i.ToCPUOutputWithContext(context.Background())
}

func (i CPUArgs) ToCPUOutputWithContext(ctx context.Context) CPUOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CPUOutput)
}

func (i CPUArgs) ToCPUPtrOutput() CPUPtrOutput {
	return i.ToCPUPtrOutputWithContext(context.Background())
}

func (i CPUArgs) ToCPUPtrOutputWithContext(ctx context.Context) CPUPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CPUOutput).ToCPUPtrOutputWithContext(ctx)
}

// CPUPtrInput is an input type that accepts CPUArgs, CPUPtr and CPUPtrOutput values.
// You can construct a concrete instance of `CPUPtrInput` via:
//
//	        CPUArgs{...}
//
//	or:
//
//	        nil
type CPUPtrInput interface {
	pulumi.Input

	ToCPUPtrOutput() CPUPtrOutput
	ToCPUPtrOutputWithContext(context.Context) CPUPtrOutput
}

type cpuPtrType CPUArgs

func CPUPtr(v *CPUArgs) CPUPtrInput {
	return (*cpuPtrType)(v)
}

func (*cpuPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**CPU)(nil)).Elem()
}

func (i *cpuPtrType) ToCPUPtrOutput() CPUPtrOutput {
	return i.ToCPUPtrOutputWithContext(context.Background())
}

func (i *cpuPtrType) ToCPUPtrOutputWithContext(ctx context.Context) CPUPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CPUPtrOutput)
}

// CPU configuration for the virtual machine.
type CPUOutput struct{ *pulumi.OutputState }

func (CPUOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CPU)(nil)).Elem()
}

func (o CPUOutput) ToCPUOutput() CPUOutput {
	return o
}

func (o CPUOutput) ToCPUOutputWithContext(ctx context.Context) CPUOutput {
	return o
}

func (o CPUOutput) ToCPUPtrOutput() CPUPtrOutput {
	return o.ToCPUPtrOutputWithContext(context.Background())
}

func (o CPUOutput) ToCPUPtrOutputWithContext(ctx context.Context) CPUPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v CPU) *CPU {
		return &v
	}).(CPUPtrOutput)
}

// Number of CPU cores per socket.
func (o CPUOutput) Cores() pulumi.IntPtrOutput {
	return o.ApplyT(func(v CPU) *int { return v.Cores }).(pulumi.IntPtrOutput)
}

// List of CPU flags to disable.
func (o CPUOutput) FlagsDisabled() pulumi.StringArrayOutput {
	return o.ApplyT(func(v CPU) []string { return v.FlagsDisabled }).(pulumi.StringArrayOutput)
}

// List of CPU flags to enable (e.g., pcid, spec-ctrl).
func (o CPUOutput) FlagsEnabled() pulumi.StringArrayOutput {
	return o.ApplyT(func(v CPU) []string { return v.FlagsEnabled }).(pulumi.StringArrayOutput)
}

// Hide VM CPU type from the guest operating system.
func (o CPUOutput) Hidden() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v CPU) *bool { return v.Hidden }).(pulumi.BoolPtrOutput)
}

// Hyper-V vendor ID presented to the guest (up to 12 characters).
func (o CPUOutput) HvVendorId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v CPU) *string { return v.HvVendorId }).(pulumi.StringPtrOutput)
}

// CPU usage limit as a fraction of one core (e.g., 1.5 caps at 150%).
func (o CPUOutput) Limit() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v CPU) *float64 { return v.Limit }).(pulumi.Float64PtrOutput)
}

// Enable NUMA topology.
func (o CPUOutput) Numa() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v CPU) *bool { return v.Numa }).(pulumi.BoolPtrOutput)
}

// NUMA node topology configuration.
func (o CPUOutput) NumaNodes() NumaNodeArrayOutput {
	return o.ApplyT(func(v CPU) []NumaNode { return v.NumaNodes }).(NumaNodeArrayOutput)
}

// Number of physical address bits exposed to the guest (e.g., 36, 40, 48).
func (o CPUOutput) PhysBits() pulumi.StringPtrOutput {
	return o.ApplyT(func(v CPU) *string { return v.PhysBits }).(pulumi.StringPtrOutput)
}

// Number of CPU sockets.
func (o CPUOutput) Sockets() pulumi.IntPtrOutput {
	return o.ApplyT(func(v CPU) *int { return v.Sockets }).(pulumi.IntPtrOutput)
}

// CPU type (e.g., host, kvm64, x86-64-v2-AES).
func (o CPUOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v CPU) *string { return v.Type }).(pulumi.StringPtrOutput)
}

// CPU weight for the scheduler relative to other VMs (higher = more CPU time).
func (o CPUOutput) Units() pulumi.IntPtrOutput {
	return o.ApplyT(func(v CPU) *int { return v.Units }).(pulumi.IntPtrOutput)
}

// Number of hotplugged vCPUs (must be <= cores * sockets).
func (o CPUOutput) Vcpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v CPU) *int { return v.Vcpus }).(pulumi.IntPtrOutput)
}

type CPUPtrOutput struct{ *pulumi.OutputState }

func (CPUPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CPU)(nil)).Elem()
}

func (o CPUPtrOutput) ToCPUPtrOutput() CPUPtrOutput {
	return o
}

func (o CPUPtrOutput) ToCPUPtrOutputWithContext(ctx context.Context) CPUPtrOutput {
	return o
}

func (o CPUPtrOutput) Elem() CPUOutput {
	return o.ApplyT(func(v *CPU) CPU {
		if v != nil {
			return *v
		}
		var ret CPU
		return ret
	}).(CPUOutput)
}

// Number of CPU cores per socket.
func (o CPUPtrOutput) Cores() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *CPU) *int {
		if v == nil {
			return nil
		}
		return v.Cores
	}).(pulumi.IntPtrOutput)
}

// List of CPU flags to disable.
func (o CPUPtrOutput) FlagsDisabled() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CPU) []string {
		if v == nil {
			return nil
		}
		return v.FlagsDisabled
	}).(pulumi.StringArrayOutput)
}

// List of CPU flags to enable (e.g., pcid, spec-ctrl).
func (o CPUPtrOutput) FlagsEnabled() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CPU) []string {
		if v == nil {
			return nil
		}
		return v.FlagsEnabled
	}).(pulumi.StringArrayOutput)
}

// Hide VM CPU type from the guest operating system.
func (o CPUPtrOutput) Hidden() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CPU) *bool {
		if v == nil {
			return nil
		}
		return v.Hidden
	}).(pulumi.BoolPtrOutput)
}

// Hyper-V vendor ID presented to the guest (up to 12 characters).
func (o CPUPtrOutput) HvVendorId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CPU) *string {
		if v == nil {
			return nil
		}
		return v.HvVendorId
	}).(pulumi.StringPtrOutput)
}

// CPU usage limit as a fraction of one core (e.g., 1.5 caps at 150%).
func (o CPUPtrOutput) Limit() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *CPU) *float64 {
		if v == nil {
			return nil
		}
		return v.Limit
	}).(pulumi.Float64PtrOutput)
}

// Enable NUMA topology.
func (o CPUPtrOutput) Numa() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CPU) *bool {
		if v == nil {
			return nil
		}
		return v.Numa
	}).(pulumi.BoolPtrOutput)
}

// NUMA node topology configuration.
func (o CPUPtrOutput) NumaNodes() NumaNodeArrayOutput {
	return o.ApplyT(func(v *CPU) []NumaNode {
		if v == nil {
			return nil
		}
		return v.NumaNodes
	}).(NumaNodeArrayOutput)
}

// Number of physical address bits exposed to the guest (e.g., 36, 40, 48).
func (o CPUPtrOutput) PhysBits() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CPU) *string {
		if v == nil {
			return nil
		}
		return v.PhysBits
	}).(pulumi.StringPtrOutput)
}

// Number of CPU sockets.
func (o CPUPtrOutput) Sockets() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *CPU) *int {
		if v == nil {
			return nil
		}
		return v.Sockets
	}).(pulumi.IntPtrOutput)
}

// CPU type (e.g., host, kvm64, x86-64-v2-AES).
func (o CPUPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CPU) *string {
		if v == nil {
			return nil
		}
		return v.Type
	}).(pulumi.StringPtrOutput)
}

// CPU weight for the scheduler relative to other VMs (higher = more CPU time).
func (o CPUPtrOutput) Units() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *CPU) *int {
		if v == nil {
			return nil
		}
		return v.Units
	}).(pulumi.IntPtrOutput)
}

// Number of hotplugged vCPUs (must be <= cores * sockets).
func (o CPUPtrOutput) Vcpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *CPU) *int {
		if v == nil {
			return nil
		}
		return v.Vcpus
	}).(pulumi.IntPtrOutput)
}

// Configuration for cloning a source virtual machine.
type Clone struct {
	// Target storage pool for the cloned disks.
	DataStoreId *string `pulumi:"dataStoreId"`
	// Create a full independent clone instead of a linked clone.
	FullClone *bool `pulumi:"fullClone"`
	// Target Proxmox node for the clone operation.
	Node *string `pulumi:"node"`
	// Timeout in seconds for the clone operation.
	Timeout *int `pulumi:"timeout"`
	// Source VM ID to clone from.
	VmId int `pulumi:"vmId"`
}

// CloneInput is an input type that accepts CloneArgs and CloneOutput values.
// You can construct a concrete instance of `CloneInput` via:
//
//	CloneArgs{...}
type CloneInput interface {
	pulumi.Input

	ToCloneOutput() CloneOutput
	ToCloneOutputWithContext(context.Context) CloneOutput
}

// Configuration for cloning a source virtual machine.
type CloneArgs struct {
	// Target storage pool for the cloned disks.
	DataStoreId pulumi.StringPtrInput `pulumi:"dataStoreId"`
	// Create a full independent clone instead of a linked clone.
	FullClone pulumi.BoolPtrInput `pulumi:"fullClone"`
	// Target Proxmox node for the clone operation.
	Node pulumi.StringPtrInput `pulumi:"node"`
	// Timeout in seconds for the clone operation.
	Timeout pulumi.IntPtrInput `pulumi:"timeout"`
	// Source VM ID to clone from.
	VmId pulumi.IntInput `pulumi:"vmId"`
}

func (CloneArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Clone)(nil)).Elem()
}

func (i CloneArgs) ToCloneOutput() CloneOutput {
	return i.ToCloneOutputWithContext(context.Background())
}

func (i CloneArgs) ToCloneOutputWithContext(ctx context.Context) CloneOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloneOutput)
}

func (i CloneArgs) ToClonePtrOutput() ClonePtrOutput {
	return i.ToClonePtrOutputWithContext(context.Background())
}

func (i CloneArgs) ToClonePtrOutputWithContext(ctx context.Context) ClonePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloneOutput).ToClonePtrOutputWithContext(ctx)
}

// ClonePtrInput is an input type that accepts CloneArgs, ClonePtr and ClonePtrOutput values.
// You can construct a concrete instance of `ClonePtrInput` via:
//
//	        CloneArgs{...}
//
//	or:
//
//	        nil
type ClonePtrInput interface {
	pulumi.Input

	ToClonePtrOutput() ClonePtrOutput
	ToClonePtrOutputWithContext(context.Context) ClonePtrOutput
}

type clonePtrType CloneArgs

func ClonePtr(v *CloneArgs) ClonePtrInput {
	return (*clonePtrType)(v)
}

func (*clonePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Clone)(nil)).Elem()
}

func (i *clonePtrType) ToClonePtrOutput() ClonePtrOutput {
	return i.ToClonePtrOutputWithContext(context.Background())
}

func (i *clonePtrType) ToClonePtrOutputWithContext(ctx context.Context) ClonePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClonePtrOutput)
}

// Configuration for cloning a source virtual machine.
type CloneOutput struct{ *pulumi.OutputState }

func (CloneOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Clone)(nil)).Elem()
}

func (o CloneOutput) ToCloneOutput() CloneOutput {
	return o
}

func (o CloneOutput) ToCloneOutputWithContext(ctx context.Context) CloneOutput {
	return o
}

func (o CloneOutput) ToClonePtrOutput() ClonePtrOutput {
	return o.ToClonePtrOutputWithContext(context.Background())
}

func (o CloneOutput) ToClonePtrOutputWithContext(ctx context.Context) ClonePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Clone) *Clone {
		return &v
	}).(ClonePtrOutput)
}

// Target storage pool for the cloned disks.
func (o CloneOutput) DataStoreId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Clone) *string { return v.DataStoreId }).(pulumi.StringPtrOutput)
}

// Create a full independent clone instead of a linked clone.
func (o CloneOutput) FullClone() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Clone) *bool { return v.FullClone }).(pulumi.BoolPtrOutput)
}

// Target Proxmox node for the clone operation.
func (o CloneOutput) Node() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Clone) *string { return v.Node }).(pulumi.StringPtrOutput)
}

// Timeout in seconds for the clone operation.
func (o CloneOutput) Timeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Clone) *int { return v.Timeout }).(pulumi.IntPtrOutput)
}

// Source VM ID to clone from.
func (o CloneOutput) VmId() pulumi.IntOutput {
	return o.ApplyT(func(v Clone) int { return v.VmId }).(pulumi.IntOutput)
}

type ClonePtrOutput struct{ *pulumi.OutputState }

func (ClonePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Clone)(nil)).Elem()
}

func (o ClonePtrOutput) ToClonePtrOutput() ClonePtrOutput {
	return o
}

func (o ClonePtrOutput) ToClonePtrOutputWithContext(ctx context.Context) ClonePtrOutput {
	return o
}

func (o ClonePtrOutput) Elem() CloneOutput {
	return o.ApplyT(func(v *Clone) Clone {
		if v != nil {
			return *v
		}
		var ret Clone
		return ret
	}).(CloneOutput)
}

// Target storage pool for the cloned disks.
func (o ClonePtrOutput) DataStoreId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Clone) *string {
		if v == nil {
			return nil
		}
		return v.DataStoreId
	}).(pulumi.StringPtrOutput)
}

// Create a full independent clone instead of a linked clone.
func (o ClonePtrOutput) FullClone() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Clone) *bool {
		if v == nil {
			return nil
		}
		return v.FullClone
	}).(pulumi.BoolPtrOutput)
}

// Target Proxmox node for the clone operation.
func (o ClonePtrOutput) Node() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Clone) *string {
		if v == nil {
			return nil
		}
		return v.Node
	}).(pulumi.StringPtrOutput)
}

// Timeout in seconds for the clone operation.
func (o ClonePtrOutput) Timeout() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Clone) *int {
		if v == nil {
			return nil
		}
		return v.Timeout
	}).(pulumi.IntPtrOutput)
}

// Source VM ID to clone from.
func (o ClonePtrOutput) VmId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Clone) *int {
		if v == nil {
			return nil
		}
		return &v.VmId
	}).(pulumi.IntPtrOutput)
}

// Disk configuration for the virtual machine.
type Disk struct {
	// File name of the disk image (computed by Proxmox if not provided).
	Filename *string `pulumi:"filename"`
	// Disk interface type and slot (e.g., scsi0, virtio0, ide1, sata2).
	Interface string `pulumi:"interface"`
	// Disk size in gigabytes.
	Size int `pulumi:"size"`
	// Target storage pool for the disk (e.g., local-lvm, ceph-pool).
	Storage string `pulumi:"storage"`
}

// DiskInput is an input type that accepts DiskArgs and DiskOutput values.
// You can construct a concrete instance of `DiskInput` via:
//
//	DiskArgs{...}
type DiskInput interface {
	pulumi.Input

	ToDiskOutput() DiskOutput
	ToDiskOutputWithContext(context.Context) DiskOutput
}

// Disk configuration for the virtual machine.
type DiskArgs struct {
	// File name of the disk image (computed by Proxmox if not provided).
	Filename pulumi.StringPtrInput `pulumi:"filename"`
	// Disk interface type and slot (e.g., scsi0, virtio0, ide1, sata2).
	Interface pulumi.StringInput `pulumi:"interface"`
	// Disk size in gigabytes.
	Size pulumi.IntInput `pulumi:"size"`
	// Target storage pool for the disk (e.g., local-lvm, ceph-pool).
	Storage pulumi.StringInput `pulumi:"storage"`
}

func (DiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Disk)(nil)).Elem()
}

func (i DiskArgs) ToDiskOutput() DiskOutput {
	return i.ToDiskOutputWithContext(context.Background())
}

func (i DiskArgs) ToDiskOutputWithContext(ctx context.Context) DiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DiskOutput)
}

// DiskArrayInput is an input type that accepts DiskArray and DiskArrayOutput values.
// You can construct a concrete instance of `DiskArrayInput` via:
//
//	DiskArray{ DiskArgs{...} }
type DiskArrayInput interface {
	pulumi.Input

	ToDiskArrayOutput() DiskArrayOutput
	ToDiskArrayOutputWithContext(context.Context) DiskArrayOutput
}

type DiskArray []DiskInput

func (DiskArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Disk)(nil)).Elem()
}

func (i DiskArray) ToDiskArrayOutput() DiskArrayOutput {
	return i.ToDiskArrayOutputWithContext(context.Background())
}

func (i DiskArray) ToDiskArrayOutputWithContext(ctx context.Context) DiskArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DiskArrayOutput)
}

// Disk configuration for the virtual machine.
type DiskOutput struct{ *pulumi.OutputState }

func (DiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Disk)(nil)).Elem()
}

func (o DiskOutput) ToDiskOutput() DiskOutput {
	return o
}

func (o DiskOutput) ToDiskOutputWithContext(ctx context.Context) DiskOutput {
	return o
}

// File name of the disk image (computed by Proxmox if not provided).
func (o DiskOutput) Filename() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Disk) *string { return v.Filename }).(pulumi.StringPtrOutput)
}

// Disk interface type and slot (e.g., scsi0, virtio0, ide1, sata2).
func (o DiskOutput) Interface() pulumi.StringOutput {
	return o.ApplyT(func(v Disk) string { return v.Interface }).(pulumi.StringOutput)
}

// Disk size in gigabytes.
func (o DiskOutput) Size() pulumi.IntOutput {
	return o.ApplyT(func(v Disk) int { return v.Size }).(pulumi.IntOutput)
}

// Target storage pool for the disk (e.g., local-lvm, ceph-pool).
func (o DiskOutput) Storage() pulumi.StringOutput {
	return o.ApplyT(func(v Disk) string { return v.Storage }).(pulumi.StringOutput)
}

type DiskArrayOutput struct{ *pulumi.OutputState }

func (DiskArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Disk)(nil)).Elem()
}

func (o DiskArrayOutput) ToDiskArrayOutput() DiskArrayOutput {
	return o
}

func (o DiskArrayOutput) ToDiskArrayOutputWithContext(ctx context.Context) DiskArrayOutput {
	return o
}

func (o DiskArrayOutput) Index(i pulumi.IntInput) DiskOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Disk {
		return vs[0].([]Disk)[vs[1].(int)]
	}).(DiskOutput)
}

// EFI disk configuration for the virtual machine.
type EfiDisk struct {
	// EFI firmware size: '2m' (2 MB, legacy) or '4m' (4 MB, supports Secure Boot).
	Efitype string `pulumi:"efitype"`
	// File name of the EFI disk image (computed by Proxmox if not provided).
	Filename *string `pulumi:"filename"`
	// Pre-enroll Microsoft and standard UEFI keys into the EFI firmware.
	PreEnrolledKeys *bool `pulumi:"preEnrolledKeys"`
	// Target storage pool for the EFI disk (e.g., local-lvm).
	Storage string `pulumi:"storage"`
}

// EfiDiskInput is an input type that accepts EfiDiskArgs and EfiDiskOutput values.
// You can construct a concrete instance of `EfiDiskInput` via:
//
//	EfiDiskArgs{...}
type EfiDiskInput interface {
	pulumi.Input

	ToEfiDiskOutput() EfiDiskOutput
	ToEfiDiskOutputWithContext(context.Context) EfiDiskOutput
}

// EFI disk configuration for the virtual machine.
type EfiDiskArgs struct {
	// EFI firmware size: '2m' (2 MB, legacy) or '4m' (4 MB, supports Secure Boot).
	Efitype pulumi.StringInput `pulumi:"efitype"`
	// File name of the EFI disk image (computed by Proxmox if not provided).
	Filename pulumi.StringPtrInput `pulumi:"filename"`
	// Pre-enroll Microsoft and standard UEFI keys into the EFI firmware.
	PreEnrolledKeys pulumi.BoolPtrInput `pulumi:"preEnrolledKeys"`
	// Target storage pool for the EFI disk (e.g., local-lvm).
	Storage pulumi.StringInput `pulumi:"storage"`
}

func (EfiDiskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*EfiDisk)(nil)).Elem()
}

func (i EfiDiskArgs) ToEfiDiskOutput() EfiDiskOutput {
	return i.ToEfiDiskOutputWithContext(context.Background())
}

func (i EfiDiskArgs) ToEfiDiskOutputWithContext(ctx context.Context) EfiDiskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EfiDiskOutput)
}

func (i EfiDiskArgs) ToEfiDiskPtrOutput() EfiDiskPtrOutput {
	return i.ToEfiDiskPtrOutputWithContext(context.Background())
}

func (i EfiDiskArgs) ToEfiDiskPtrOutputWithContext(ctx context.Context) EfiDiskPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EfiDiskOutput).ToEfiDiskPtrOutputWithContext(ctx)
}

// EfiDiskPtrInput is an input type that accepts EfiDiskArgs, EfiDiskPtr and EfiDiskPtrOutput values.
// You can construct a concrete instance of `EfiDiskPtrInput` via:
//
//	        EfiDiskArgs{...}
//
//	or:
//
//	        nil
type EfiDiskPtrInput interface {
	pulumi.Input

	ToEfiDiskPtrOutput() EfiDiskPtrOutput
	ToEfiDiskPtrOutputWithContext(context.Context) EfiDiskPtrOutput
}

type efiDiskPtrType EfiDiskArgs

func EfiDiskPtr(v *EfiDiskArgs) EfiDiskPtrInput {
	return (*efiDiskPtrType)(v)
}

func (*efiDiskPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**EfiDisk)(nil)).Elem()
}

func (i *efiDiskPtrType) ToEfiDiskPtrOutput() EfiDiskPtrOutput {
	return i.ToEfiDiskPtrOutputWithContext(context.Background())
}

func (i *efiDiskPtrType) ToEfiDiskPtrOutputWithContext(ctx context.Context) EfiDiskPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EfiDiskPtrOutput)
}

// EFI disk configuration for the virtual machine.
type EfiDiskOutput struct{ *pulumi.OutputState }

func (EfiDiskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EfiDisk)(nil)).Elem()
}

func (o EfiDiskOutput) ToEfiDiskOutput() EfiDiskOutput {
	return o
}

func (o EfiDiskOutput) ToEfiDiskOutputWithContext(ctx context.Context) EfiDiskOutput {
	return o
}

func (o EfiDiskOutput) ToEfiDiskPtrOutput() EfiDiskPtrOutput {
	return o.ToEfiDiskPtrOutputWithContext(context.Background())
}

func (o EfiDiskOutput) ToEfiDiskPtrOutputWithContext(ctx context.Context) EfiDiskPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v EfiDisk) *EfiDisk {
		return &v
	}).(EfiDiskPtrOutput)
}

// EFI firmware size: '2m' (2 MB, legacy) or '4m' (4 MB, supports Secure Boot).
func (o EfiDiskOutput) Efitype() pulumi.StringOutput {
	return o.ApplyT(func(v EfiDisk) string { return v.Efitype }).(pulumi.StringOutput)
}

// File name of the EFI disk image (computed by Proxmox if not provided).
func (o EfiDiskOutput) Filename() pulumi.StringPtrOutput {
	return o.ApplyT(func(v EfiDisk) *string { return v.Filename }).(pulumi.StringPtrOutput)
}

// Pre-enroll Microsoft and standard UEFI keys into the EFI firmware.
func (o EfiDiskOutput) PreEnrolledKeys() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v EfiDisk) *bool { return v.PreEnrolledKeys }).(pulumi.BoolPtrOutput)
}

// Target storage pool for the EFI disk (e.g., local-lvm).
func (o EfiDiskOutput) Storage() pulumi.StringOutput {
	return o.ApplyT(func(v EfiDisk) string { return v.Storage }).(pulumi.StringOutput)
}

type EfiDiskPtrOutput struct{ *pulumi.OutputState }

func (EfiDiskPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EfiDisk)(nil)).Elem()
}

func (o EfiDiskPtrOutput) ToEfiDiskPtrOutput() EfiDiskPtrOutput {
	return o
}

func (o EfiDiskPtrOutput) ToEfiDiskPtrOutputWithContext(ctx context.Context) EfiDiskPtrOutput {
	return o
}

func (o EfiDiskPtrOutput) Elem() EfiDiskOutput {
	return o.ApplyT(func(v *EfiDisk) EfiDisk {
		if v != nil {
			return *v
		}
		var ret EfiDisk
		return ret
	}).(EfiDiskOutput)
}

// EFI firmware size: '2m' (2 MB, legacy) or '4m' (4 MB, supports Secure Boot).
func (o EfiDiskPtrOutput) Efitype() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EfiDisk) *string {
		if v == nil {
			return nil
		}
		return &v.Efitype
	}).(pulumi.StringPtrOutput)
}

// File name of the EFI disk image (computed by Proxmox if not provided).
func (o EfiDiskPtrOutput) Filename() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EfiDisk) *string {
		if v == nil {
			return nil
		}
		return v.Filename
	}).(pulumi.StringPtrOutput)
}

// Pre-enroll Microsoft and standard UEFI keys into the EFI firmware.
func (o EfiDiskPtrOutput) PreEnrolledKeys() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EfiDisk) *bool {
		if v == nil {
			return nil
		}
		return v.PreEnrolledKeys
	}).(pulumi.BoolPtrOutput)
}

// Target storage pool for the EFI disk (e.g., local-lvm).
func (o EfiDiskPtrOutput) Storage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EfiDisk) *string {
		if v == nil {
			return nil
		}
		return &v.Storage
	}).(pulumi.StringPtrOutput)
}

type FileSourceRaw struct {
	// The raw data in []byte
	FileData string `pulumi:"fileData"`
	// The name of the file
	FileName string `pulumi:"fileName"`
}

// FileSourceRawInput is an input type that accepts FileSourceRawArgs and FileSourceRawOutput values.
// You can construct a concrete instance of `FileSourceRawInput` via:
//
//	FileSourceRawArgs{...}
type FileSourceRawInput interface {
	pulumi.Input

	ToFileSourceRawOutput() FileSourceRawOutput
	ToFileSourceRawOutputWithContext(context.Context) FileSourceRawOutput
}

type FileSourceRawArgs struct {
	// The raw data in []byte
	FileData pulumi.StringInput `pulumi:"fileData"`
	// The name of the file
	FileName pulumi.StringInput `pulumi:"fileName"`
}

func (FileSourceRawArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*FileSourceRaw)(nil)).Elem()
}

func (i FileSourceRawArgs) ToFileSourceRawOutput() FileSourceRawOutput {
	return i.ToFileSourceRawOutputWithContext(context.Background())
}

func (i FileSourceRawArgs) ToFileSourceRawOutputWithContext(ctx context.Context) FileSourceRawOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FileSourceRawOutput)
}

type FileSourceRawOutput struct{ *pulumi.OutputState }

func (FileSourceRawOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FileSourceRaw)(nil)).Elem()
}

func (o FileSourceRawOutput) ToFileSourceRawOutput() FileSourceRawOutput {
	return o
}

func (o FileSourceRawOutput) ToFileSourceRawOutputWithContext(ctx context.Context) FileSourceRawOutput {
	return o
}

// The raw data in []byte
func (o FileSourceRawOutput) FileData() pulumi.StringOutput {
	return o.ApplyT(func(v FileSourceRaw) string { return v.FileData }).(pulumi.StringOutput)
}

// The name of the file
func (o FileSourceRawOutput) FileName() pulumi.StringOutput {
	return o.ApplyT(func(v FileSourceRaw) string { return v.FileName }).(pulumi.StringOutput)
}

// NUMA node topology configuration for the virtual machine.
type NumaNode struct {
	// CPUs (and optionally threads) assigned to this NUMA node (e.g., 0-3).
	Cpus string `pulumi:"cpus"`
	// Host NUMA nodes to map to this virtual NUMA node (e.g., 0-1).
	HostNodes *string `pulumi:"hostNodes"`
	// Memory in megabytes allocated to this NUMA node.
	Memory *int `pulumi:"memory"`
	// NUMA memory allocation policy (preferred, bind, interleave, or mpol).
	Policy *string `pulumi:"policy"`
}

// NumaNodeInput is an input type that accepts NumaNodeArgs and NumaNodeOutput values.
// You can construct a concrete instance of `NumaNodeInput` via:
//
//	NumaNodeArgs{...}
type NumaNodeInput interface {
	pulumi.Input

	ToNumaNodeOutput() NumaNodeOutput
	ToNumaNodeOutputWithContext(context.Context) NumaNodeOutput
}

// NUMA node topology configuration for the virtual machine.
type NumaNodeArgs struct {
	// CPUs (and optionally threads) assigned to this NUMA node (e.g., 0-3).
	Cpus pulumi.StringInput `pulumi:"cpus"`
	// Host NUMA nodes to map to this virtual NUMA node (e.g., 0-1).
	HostNodes pulumi.StringPtrInput `pulumi:"hostNodes"`
	// Memory in megabytes allocated to this NUMA node.
	Memory pulumi.IntPtrInput `pulumi:"memory"`
	// NUMA memory allocation policy (preferred, bind, interleave, or mpol).
	Policy pulumi.StringPtrInput `pulumi:"policy"`
}

func (NumaNodeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NumaNode)(nil)).Elem()
}

func (i NumaNodeArgs) ToNumaNodeOutput() NumaNodeOutput {
	return i.ToNumaNodeOutputWithContext(context.Background())
}

func (i NumaNodeArgs) ToNumaNodeOutputWithContext(ctx context.Context) NumaNodeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NumaNodeOutput)
}

// NumaNodeArrayInput is an input type that accepts NumaNodeArray and NumaNodeArrayOutput values.
// You can construct a concrete instance of `NumaNodeArrayInput` via:
//
//	NumaNodeArray{ NumaNodeArgs{...} }
type NumaNodeArrayInput interface {
	pulumi.Input

	ToNumaNodeArrayOutput() NumaNodeArrayOutput
	ToNumaNodeArrayOutputWithContext(context.Context) NumaNodeArrayOutput
}

type NumaNodeArray []NumaNodeInput

func (NumaNodeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NumaNode)(nil)).Elem()
}

func (i NumaNodeArray) ToNumaNodeArrayOutput() NumaNodeArrayOutput {
	return i.ToNumaNodeArrayOutputWithContext(context.Background())
}

func (i NumaNodeArray) ToNumaNodeArrayOutputWithContext(ctx context.Context) NumaNodeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NumaNodeArrayOutput)
}

// NUMA node topology configuration for the virtual machine.
type NumaNodeOutput struct{ *pulumi.OutputState }

func (NumaNodeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NumaNode)(nil)).Elem()
}

func (o NumaNodeOutput) ToNumaNodeOutput() NumaNodeOutput {
	return o
}

func (o NumaNodeOutput) ToNumaNodeOutputWithContext(ctx context.Context) NumaNodeOutput {
	return o
}

// CPUs (and optionally threads) assigned to this NUMA node (e.g., 0-3).
func (o NumaNodeOutput) Cpus() pulumi.StringOutput {
	return o.ApplyT(func(v NumaNode) string { return v.Cpus }).(pulumi.StringOutput)
}

// Host NUMA nodes to map to this virtual NUMA node (e.g., 0-1).
func (o NumaNodeOutput) HostNodes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v NumaNode) *string { return v.HostNodes }).(pulumi.StringPtrOutput)
}

// Memory in megabytes allocated to this NUMA node.
func (o NumaNodeOutput) Memory() pulumi.IntPtrOutput {
	return o.ApplyT(func(v NumaNode) *int { return v.Memory }).(pulumi.IntPtrOutput)
}

// NUMA memory allocation policy (preferred, bind, interleave, or mpol).
func (o NumaNodeOutput) Policy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v NumaNode) *string { return v.Policy }).(pulumi.StringPtrOutput)
}

type NumaNodeArrayOutput struct{ *pulumi.OutputState }

func (NumaNodeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]NumaNode)(nil)).Elem()
}

func (o NumaNodeArrayOutput) ToNumaNodeArrayOutput() NumaNodeArrayOutput {
	return o
}

func (o NumaNodeArrayOutput) ToNumaNodeArrayOutputWithContext(ctx context.Context) NumaNodeArrayOutput {
	return o
}

func (o NumaNodeArrayOutput) Index(i pulumi.IntInput) NumaNodeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) NumaNode {
		return vs[0].([]NumaNode)[vs[1].(int)]
	}).(NumaNodeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CPUInput)(nil)).Elem(), CPUArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CPUPtrInput)(nil)).Elem(), CPUArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloneInput)(nil)).Elem(), CloneArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClonePtrInput)(nil)).Elem(), CloneArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DiskInput)(nil)).Elem(), DiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DiskArrayInput)(nil)).Elem(), DiskArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EfiDiskInput)(nil)).Elem(), EfiDiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*EfiDiskPtrInput)(nil)).Elem(), EfiDiskArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*FileSourceRawInput)(nil)).Elem(), FileSourceRawArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NumaNodeInput)(nil)).Elem(), NumaNodeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NumaNodeArrayInput)(nil)).Elem(), NumaNodeArray{})
	pulumi.RegisterOutputType(CPUOutput{})
	pulumi.RegisterOutputType(CPUPtrOutput{})
	pulumi.RegisterOutputType(CloneOutput{})
	pulumi.RegisterOutputType(ClonePtrOutput{})
	pulumi.RegisterOutputType(DiskOutput{})
	pulumi.RegisterOutputType(DiskArrayOutput{})
	pulumi.RegisterOutputType(EfiDiskOutput{})
	pulumi.RegisterOutputType(EfiDiskPtrOutput{})
	pulumi.RegisterOutputType(FileSourceRawOutput{})
	pulumi.RegisterOutputType(NumaNodeOutput{})
	pulumi.RegisterOutputType(NumaNodeArrayOutput{})
}
