// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.User
{
    [PveResourceType("pve:user:User")]
    public partial class User : global::Pulumi.CustomResource
    {
        /// <summary>
        /// An optional comment for the user.
        /// </summary>
        [Output("comment")]
        public Output<string?> Comment { get; private set; } = null!;

        /// <summary>
        /// An optional email address for the user.
        /// </summary>
        [Output("email")]
        public Output<string?> Email { get; private set; } = null!;

        /// <summary>
        /// Whether the user is enabled. Defaults to true.
        /// </summary>
        [Output("enable")]
        public Output<bool?> Enable { get; private set; } = null!;

        /// <summary>
        /// The expiration time for the user as a Unix timestamp.
        /// </summary>
        [Output("expire")]
        public Output<int?> Expire { get; private set; } = null!;

        /// <summary>
        /// The first name of the user.
        /// </summary>
        [Output("firstname")]
        public Output<string?> Firstname { get; private set; } = null!;

        /// <summary>
        /// A list of groups the user belongs to.
        /// </summary>
        [Output("groups")]
        public Output<ImmutableArray<string>> Groups { get; private set; } = null!;

        /// <summary>
        /// A list of SSH keys associated with the user.
        /// </summary>
        [Output("keys")]
        public Output<ImmutableArray<string>> Keys { get; private set; } = null!;

        /// <summary>
        /// The last name of the user.
        /// </summary>
        [Output("lastname")]
        public Output<string?> Lastname { get; private set; } = null!;

        /// <summary>
        /// The password for the user. This field is treated as a secret.
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// The user ID of the Proxmox user, including the realm (e.g., 'user@pve').
        /// </summary>
        [Output("userid")]
        public Output<string> Userid { get; private set; } = null!;


        /// <summary>
        /// Create a User resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public User(string name, UserArgs args, CustomResourceOptions? options = null)
            : base("pve:user:User", name, args ?? new UserArgs(), MakeResourceOptions(options, ""))
        {
        }

        private User(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pve:user:User", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "password",
                },
                ReplaceOnChanges =
                {
                    "password",
                    "userid",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing User resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static User Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new User(name, id, options);
        }
    }

    public sealed class UserArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// An optional comment for the user.
        /// </summary>
        [Input("comment")]
        public Input<string>? Comment { get; set; }

        /// <summary>
        /// An optional email address for the user.
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        /// <summary>
        /// Whether the user is enabled. Defaults to true.
        /// </summary>
        [Input("enable")]
        public Input<bool>? Enable { get; set; }

        /// <summary>
        /// The expiration time for the user as a Unix timestamp.
        /// </summary>
        [Input("expire")]
        public Input<int>? Expire { get; set; }

        /// <summary>
        /// The first name of the user.
        /// </summary>
        [Input("firstname")]
        public Input<string>? Firstname { get; set; }

        [Input("groups")]
        private InputList<string>? _groups;

        /// <summary>
        /// A list of groups the user belongs to.
        /// </summary>
        public InputList<string> Groups
        {
            get => _groups ?? (_groups = new InputList<string>());
            set => _groups = value;
        }

        [Input("keys")]
        private InputList<string>? _keys;

        /// <summary>
        /// A list of SSH keys associated with the user.
        /// </summary>
        public InputList<string> Keys
        {
            get => _keys ?? (_keys = new InputList<string>());
            set => _keys = value;
        }

        /// <summary>
        /// The last name of the user.
        /// </summary>
        [Input("lastname")]
        public Input<string>? Lastname { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The password for the user. This field is treated as a secret.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The user ID of the Proxmox user, including the realm (e.g., 'user@pve').
        /// </summary>
        [Input("userid", required: true)]
        public Input<string> Userid { get; set; } = null!;

        public UserArgs()
        {
            Enable = true;
        }
        public static new UserArgs Empty => new UserArgs();
    }
}
