// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pve.Storage.Inputs
{

    public sealed class FileSourceRawArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The raw data in []byte
        /// </summary>
        [Input("fileData", required: true)]
        public Input<string> FileData { get; set; } = null!;

        /// <summary>
        /// The name of the file
        /// </summary>
        [Input("fileName", required: true)]
        public Input<string> FileName { get; set; } = null!;

        public FileSourceRawArgs()
        {
        }
        public static new FileSourceRawArgs Empty => new FileSourceRawArgs();
    }
}
