// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve.proxmox.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Configuration for cloning a source virtual machine.
 * 
 */
public final class CloneArgs extends com.pulumi.resources.ResourceArgs {

    public static final CloneArgs Empty = new CloneArgs();

    /**
     * Target storage pool for the cloned disks.
     * 
     */
    @Import(name="dataStoreId")
    private @Nullable Output<String> dataStoreId;

    /**
     * @return Target storage pool for the cloned disks.
     * 
     */
    public Optional<Output<String>> dataStoreId() {
        return Optional.ofNullable(this.dataStoreId);
    }

    /**
     * Create a full independent clone instead of a linked clone.
     * 
     */
    @Import(name="fullClone")
    private @Nullable Output<Boolean> fullClone;

    /**
     * @return Create a full independent clone instead of a linked clone.
     * 
     */
    public Optional<Output<Boolean>> fullClone() {
        return Optional.ofNullable(this.fullClone);
    }

    /**
     * Target Proxmox node for the clone operation.
     * 
     */
    @Import(name="node")
    private @Nullable Output<String> node;

    /**
     * @return Target Proxmox node for the clone operation.
     * 
     */
    public Optional<Output<String>> node() {
        return Optional.ofNullable(this.node);
    }

    /**
     * Timeout in seconds for the clone operation.
     * 
     */
    @Import(name="timeout")
    private @Nullable Output<Integer> timeout;

    /**
     * @return Timeout in seconds for the clone operation.
     * 
     */
    public Optional<Output<Integer>> timeout() {
        return Optional.ofNullable(this.timeout);
    }

    /**
     * Source VM ID to clone from.
     * 
     */
    @Import(name="vmId", required=true)
    private Output<Integer> vmId;

    /**
     * @return Source VM ID to clone from.
     * 
     */
    public Output<Integer> vmId() {
        return this.vmId;
    }

    private CloneArgs() {}

    private CloneArgs(CloneArgs $) {
        this.dataStoreId = $.dataStoreId;
        this.fullClone = $.fullClone;
        this.node = $.node;
        this.timeout = $.timeout;
        this.vmId = $.vmId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CloneArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CloneArgs $;

        public Builder() {
            $ = new CloneArgs();
        }

        public Builder(CloneArgs defaults) {
            $ = new CloneArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param dataStoreId Target storage pool for the cloned disks.
         * 
         * @return builder
         * 
         */
        public Builder dataStoreId(@Nullable Output<String> dataStoreId) {
            $.dataStoreId = dataStoreId;
            return this;
        }

        /**
         * @param dataStoreId Target storage pool for the cloned disks.
         * 
         * @return builder
         * 
         */
        public Builder dataStoreId(String dataStoreId) {
            return dataStoreId(Output.of(dataStoreId));
        }

        /**
         * @param fullClone Create a full independent clone instead of a linked clone.
         * 
         * @return builder
         * 
         */
        public Builder fullClone(@Nullable Output<Boolean> fullClone) {
            $.fullClone = fullClone;
            return this;
        }

        /**
         * @param fullClone Create a full independent clone instead of a linked clone.
         * 
         * @return builder
         * 
         */
        public Builder fullClone(Boolean fullClone) {
            return fullClone(Output.of(fullClone));
        }

        /**
         * @param node Target Proxmox node for the clone operation.
         * 
         * @return builder
         * 
         */
        public Builder node(@Nullable Output<String> node) {
            $.node = node;
            return this;
        }

        /**
         * @param node Target Proxmox node for the clone operation.
         * 
         * @return builder
         * 
         */
        public Builder node(String node) {
            return node(Output.of(node));
        }

        /**
         * @param timeout Timeout in seconds for the clone operation.
         * 
         * @return builder
         * 
         */
        public Builder timeout(@Nullable Output<Integer> timeout) {
            $.timeout = timeout;
            return this;
        }

        /**
         * @param timeout Timeout in seconds for the clone operation.
         * 
         * @return builder
         * 
         */
        public Builder timeout(Integer timeout) {
            return timeout(Output.of(timeout));
        }

        /**
         * @param vmId Source VM ID to clone from.
         * 
         * @return builder
         * 
         */
        public Builder vmId(Output<Integer> vmId) {
            $.vmId = vmId;
            return this;
        }

        /**
         * @param vmId Source VM ID to clone from.
         * 
         * @return builder
         * 
         */
        public Builder vmId(Integer vmId) {
            return vmId(Output.of(vmId));
        }

        public CloneArgs build() {
            if ($.vmId == null) {
                throw new MissingRequiredPropertyException("CloneArgs", "vmId");
            }
            return $;
        }
    }

}
