// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve.user;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class UserArgs extends com.pulumi.resources.ResourceArgs {

    public static final UserArgs Empty = new UserArgs();

    @Import(name="comment")
    private @Nullable Output<String> comment;

    public Optional<Output<String>> comment() {
        return Optional.ofNullable(this.comment);
    }

    @Import(name="email")
    private @Nullable Output<String> email;

    public Optional<Output<String>> email() {
        return Optional.ofNullable(this.email);
    }

    @Import(name="enable")
    private @Nullable Output<Boolean> enable;

    public Optional<Output<Boolean>> enable() {
        return Optional.ofNullable(this.enable);
    }

    @Import(name="expire")
    private @Nullable Output<Integer> expire;

    public Optional<Output<Integer>> expire() {
        return Optional.ofNullable(this.expire);
    }

    @Import(name="firstname")
    private @Nullable Output<String> firstname;

    public Optional<Output<String>> firstname() {
        return Optional.ofNullable(this.firstname);
    }

    @Import(name="groups")
    private @Nullable Output<List<String>> groups;

    public Optional<Output<List<String>>> groups() {
        return Optional.ofNullable(this.groups);
    }

    @Import(name="keys")
    private @Nullable Output<List<String>> keys;

    public Optional<Output<List<String>>> keys() {
        return Optional.ofNullable(this.keys);
    }

    @Import(name="lastname")
    private @Nullable Output<String> lastname;

    public Optional<Output<String>> lastname() {
        return Optional.ofNullable(this.lastname);
    }

    @Import(name="password")
    private @Nullable Output<String> password;

    public Optional<Output<String>> password() {
        return Optional.ofNullable(this.password);
    }

    @Import(name="userid", required=true)
    private Output<String> userid;

    public Output<String> userid() {
        return this.userid;
    }

    private UserArgs() {}

    private UserArgs(UserArgs $) {
        this.comment = $.comment;
        this.email = $.email;
        this.enable = $.enable;
        this.expire = $.expire;
        this.firstname = $.firstname;
        this.groups = $.groups;
        this.keys = $.keys;
        this.lastname = $.lastname;
        this.password = $.password;
        this.userid = $.userid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(UserArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private UserArgs $;

        public Builder() {
            $ = new UserArgs();
        }

        public Builder(UserArgs defaults) {
            $ = new UserArgs(Objects.requireNonNull(defaults));
        }

        public Builder comment(@Nullable Output<String> comment) {
            $.comment = comment;
            return this;
        }

        public Builder comment(String comment) {
            return comment(Output.of(comment));
        }

        public Builder email(@Nullable Output<String> email) {
            $.email = email;
            return this;
        }

        public Builder email(String email) {
            return email(Output.of(email));
        }

        public Builder enable(@Nullable Output<Boolean> enable) {
            $.enable = enable;
            return this;
        }

        public Builder enable(Boolean enable) {
            return enable(Output.of(enable));
        }

        public Builder expire(@Nullable Output<Integer> expire) {
            $.expire = expire;
            return this;
        }

        public Builder expire(Integer expire) {
            return expire(Output.of(expire));
        }

        public Builder firstname(@Nullable Output<String> firstname) {
            $.firstname = firstname;
            return this;
        }

        public Builder firstname(String firstname) {
            return firstname(Output.of(firstname));
        }

        public Builder groups(@Nullable Output<List<String>> groups) {
            $.groups = groups;
            return this;
        }

        public Builder groups(List<String> groups) {
            return groups(Output.of(groups));
        }

        public Builder groups(String... groups) {
            return groups(List.of(groups));
        }

        public Builder keys(@Nullable Output<List<String>> keys) {
            $.keys = keys;
            return this;
        }

        public Builder keys(List<String> keys) {
            return keys(Output.of(keys));
        }

        public Builder keys(String... keys) {
            return keys(List.of(keys));
        }

        public Builder lastname(@Nullable Output<String> lastname) {
            $.lastname = lastname;
            return this;
        }

        public Builder lastname(String lastname) {
            return lastname(Output.of(lastname));
        }

        public Builder password(@Nullable Output<String> password) {
            $.password = password;
            return this;
        }

        public Builder password(String password) {
            return password(Output.of(password));
        }

        public Builder userid(Output<String> userid) {
            $.userid = userid;
            return this;
        }

        public Builder userid(String userid) {
            return userid(Output.of(userid));
        }

        public UserArgs build() {
            if ($.userid == null) {
                throw new MissingRequiredPropertyException("UserArgs", "userid");
            }
            return $;
        }
    }

}
