// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve.sdn_zone;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VxlanZoneArgs extends com.pulumi.resources.ResourceArgs {

    public static final VxlanZoneArgs Empty = new VxlanZoneArgs();

    /**
     * DNS plugin ID associated with this zone.
     * 
     */
    @Import(name="dns")
    private @Nullable Output<String> dns;

    /**
     * @return DNS plugin ID associated with this zone.
     * 
     */
    public Optional<Output<String>> dns() {
        return Optional.ofNullable(this.dns);
    }

    /**
     * DNS zone/domain name used for host registrations.
     * 
     */
    @Import(name="dnsZone")
    private @Nullable Output<String> dnsZone;

    /**
     * @return DNS zone/domain name used for host registrations.
     * 
     */
    public Optional<Output<String>> dnsZone() {
        return Optional.ofNullable(this.dnsZone);
    }

    /**
     * SDN fabric identifier used to connect this VXLAN zone to an EVPN fabric.
     * 
     */
    @Import(name="fabric")
    private @Nullable Output<String> fabric;

    /**
     * @return SDN fabric identifier used to connect this VXLAN zone to an EVPN fabric.
     * 
     */
    public Optional<Output<String>> fabric() {
        return Optional.ofNullable(this.fabric);
    }

    /**
     * IPAM plugin ID associated with this zone.
     * 
     */
    @Import(name="ipam", required=true)
    private Output<String> ipam;

    /**
     * @return IPAM plugin ID associated with this zone.
     * 
     */
    public Output<String> ipam() {
        return this.ipam;
    }

    /**
     * MTU for the VXLAN zone. If unset, Proxmox uses its automatic/default MTU.
     * 
     */
    @Import(name="mtu")
    private @Nullable Output<Integer> mtu;

    /**
     * @return MTU for the VXLAN zone. If unset, Proxmox uses its automatic/default MTU.
     * 
     */
    public Optional<Output<Integer>> mtu() {
        return Optional.ofNullable(this.mtu);
    }

    /**
     * The unique VXLAN zone name.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The unique VXLAN zone name.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Cluster nodes where this zone is active.
     * 
     */
    @Import(name="nodes")
    private @Nullable Output<List<String>> nodes;

    /**
     * @return Cluster nodes where this zone is active.
     * 
     */
    public Optional<Output<List<String>>> nodes() {
        return Optional.ofNullable(this.nodes);
    }

    /**
     * A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
     * 
     */
    @Import(name="peers")
    private @Nullable Output<List<String>> peers;

    /**
     * @return A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
     * 
     */
    public Optional<Output<List<String>>> peers() {
        return Optional.ofNullable(this.peers);
    }

    /**
     * Reverse DNS plugin ID associated with this zone.
     * 
     */
    @Import(name="reverseDns")
    private @Nullable Output<String> reverseDns;

    /**
     * @return Reverse DNS plugin ID associated with this zone.
     * 
     */
    public Optional<Output<String>> reverseDns() {
        return Optional.ofNullable(this.reverseDns);
    }

    /**
     * UDP destination port used for VXLAN encapsulation.
     * 
     */
    @Import(name="vxlanPort")
    private @Nullable Output<Integer> vxlanPort;

    /**
     * @return UDP destination port used for VXLAN encapsulation.
     * 
     */
    public Optional<Output<Integer>> vxlanPort() {
        return Optional.ofNullable(this.vxlanPort);
    }

    private VxlanZoneArgs() {}

    private VxlanZoneArgs(VxlanZoneArgs $) {
        this.dns = $.dns;
        this.dnsZone = $.dnsZone;
        this.fabric = $.fabric;
        this.ipam = $.ipam;
        this.mtu = $.mtu;
        this.name = $.name;
        this.nodes = $.nodes;
        this.peers = $.peers;
        this.reverseDns = $.reverseDns;
        this.vxlanPort = $.vxlanPort;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VxlanZoneArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VxlanZoneArgs $;

        public Builder() {
            $ = new VxlanZoneArgs();
        }

        public Builder(VxlanZoneArgs defaults) {
            $ = new VxlanZoneArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param dns DNS plugin ID associated with this zone.
         * 
         * @return builder
         * 
         */
        public Builder dns(@Nullable Output<String> dns) {
            $.dns = dns;
            return this;
        }

        /**
         * @param dns DNS plugin ID associated with this zone.
         * 
         * @return builder
         * 
         */
        public Builder dns(String dns) {
            return dns(Output.of(dns));
        }

        /**
         * @param dnsZone DNS zone/domain name used for host registrations.
         * 
         * @return builder
         * 
         */
        public Builder dnsZone(@Nullable Output<String> dnsZone) {
            $.dnsZone = dnsZone;
            return this;
        }

        /**
         * @param dnsZone DNS zone/domain name used for host registrations.
         * 
         * @return builder
         * 
         */
        public Builder dnsZone(String dnsZone) {
            return dnsZone(Output.of(dnsZone));
        }

        /**
         * @param fabric SDN fabric identifier used to connect this VXLAN zone to an EVPN fabric.
         * 
         * @return builder
         * 
         */
        public Builder fabric(@Nullable Output<String> fabric) {
            $.fabric = fabric;
            return this;
        }

        /**
         * @param fabric SDN fabric identifier used to connect this VXLAN zone to an EVPN fabric.
         * 
         * @return builder
         * 
         */
        public Builder fabric(String fabric) {
            return fabric(Output.of(fabric));
        }

        /**
         * @param ipam IPAM plugin ID associated with this zone.
         * 
         * @return builder
         * 
         */
        public Builder ipam(Output<String> ipam) {
            $.ipam = ipam;
            return this;
        }

        /**
         * @param ipam IPAM plugin ID associated with this zone.
         * 
         * @return builder
         * 
         */
        public Builder ipam(String ipam) {
            return ipam(Output.of(ipam));
        }

        /**
         * @param mtu MTU for the VXLAN zone. If unset, Proxmox uses its automatic/default MTU.
         * 
         * @return builder
         * 
         */
        public Builder mtu(@Nullable Output<Integer> mtu) {
            $.mtu = mtu;
            return this;
        }

        /**
         * @param mtu MTU for the VXLAN zone. If unset, Proxmox uses its automatic/default MTU.
         * 
         * @return builder
         * 
         */
        public Builder mtu(Integer mtu) {
            return mtu(Output.of(mtu));
        }

        /**
         * @param name The unique VXLAN zone name.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The unique VXLAN zone name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param nodes Cluster nodes where this zone is active.
         * 
         * @return builder
         * 
         */
        public Builder nodes(@Nullable Output<List<String>> nodes) {
            $.nodes = nodes;
            return this;
        }

        /**
         * @param nodes Cluster nodes where this zone is active.
         * 
         * @return builder
         * 
         */
        public Builder nodes(List<String> nodes) {
            return nodes(Output.of(nodes));
        }

        /**
         * @param nodes Cluster nodes where this zone is active.
         * 
         * @return builder
         * 
         */
        public Builder nodes(String... nodes) {
            return nodes(List.of(nodes));
        }

        /**
         * @param peers A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
         * 
         * @return builder
         * 
         */
        public Builder peers(@Nullable Output<List<String>> peers) {
            $.peers = peers;
            return this;
        }

        /**
         * @param peers A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
         * 
         * @return builder
         * 
         */
        public Builder peers(List<String> peers) {
            return peers(Output.of(peers));
        }

        /**
         * @param peers A list of peer IP addresses in the VXLAN underlay network. Note: peers are not returned by the Proxmox API on read and will not be refreshed by `pulumi refresh`.
         * 
         * @return builder
         * 
         */
        public Builder peers(String... peers) {
            return peers(List.of(peers));
        }

        /**
         * @param reverseDns Reverse DNS plugin ID associated with this zone.
         * 
         * @return builder
         * 
         */
        public Builder reverseDns(@Nullable Output<String> reverseDns) {
            $.reverseDns = reverseDns;
            return this;
        }

        /**
         * @param reverseDns Reverse DNS plugin ID associated with this zone.
         * 
         * @return builder
         * 
         */
        public Builder reverseDns(String reverseDns) {
            return reverseDns(Output.of(reverseDns));
        }

        /**
         * @param vxlanPort UDP destination port used for VXLAN encapsulation.
         * 
         * @return builder
         * 
         */
        public Builder vxlanPort(@Nullable Output<Integer> vxlanPort) {
            $.vxlanPort = vxlanPort;
            return this;
        }

        /**
         * @param vxlanPort UDP destination port used for VXLAN encapsulation.
         * 
         * @return builder
         * 
         */
        public Builder vxlanPort(Integer vxlanPort) {
            return vxlanPort(Output.of(vxlanPort));
        }

        public VxlanZoneArgs build() {
            if ($.ipam == null) {
                throw new MissingRequiredPropertyException("VxlanZoneArgs", "ipam");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("VxlanZoneArgs", "name");
            }
            $.vxlanPort = Codegen.integerProp("vxlanPort").output().arg($.vxlanPort).def(4789).getNullable();
            return $;
        }
    }

}
