// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.Acl
{
    /// <summary>
    /// A Proxmox ACL resource that controls access to Proxmox objects.
    /// </summary>
    [PveResourceType("pve:acl:ACL")]
    public partial class ACL : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The path of the ACL.
        /// </summary>
        [Output("path")]
        public Output<string> Path { get; private set; } = null!;

        /// <summary>
        /// Whether the ACL should propagate to child objects.
        /// </summary>
        [Output("propagate")]
        public Output<bool?> Propagate { get; private set; } = null!;

        /// <summary>
        /// The role ID of the ACL.
        /// </summary>
        [Output("roleid")]
        public Output<string> Roleid { get; private set; } = null!;

        /// <summary>
        /// The type of the ACL. Must be one of 'user', 'group', or 'token'.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// The user, group, or token ID associated with the ACL.
        /// </summary>
        [Output("ugid")]
        public Output<string> Ugid { get; private set; } = null!;


        /// <summary>
        /// Create a ACL resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ACL(string name, ACLArgs args, CustomResourceOptions? options = null)
            : base("pve:acl:ACL", name, args ?? new ACLArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ACL(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pve:acl:ACL", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                ReplaceOnChanges =
                {
                    "path",
                    "propagate",
                    "roleid",
                    "type",
                    "ugid",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ACL resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ACL Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ACL(name, id, options);
        }
    }

    public sealed class ACLArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The path of the ACL.
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        /// <summary>
        /// Whether the ACL should propagate to child objects.
        /// </summary>
        [Input("propagate")]
        public Input<bool>? Propagate { get; set; }

        /// <summary>
        /// The role ID of the ACL.
        /// </summary>
        [Input("roleid", required: true)]
        public Input<string> Roleid { get; set; } = null!;

        /// <summary>
        /// The type of the ACL. Must be one of 'user', 'group', or 'token'.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// The user, group, or token ID associated with the ACL.
        /// </summary>
        [Input("ugid", required: true)]
        public Input<string> Ugid { get; set; } = null!;

        public ACLArgs()
        {
        }
        public static new ACLArgs Empty => new ACLArgs();
    }
}
