# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['ACLArgs', 'ACL']

@pulumi.input_type
class ACLArgs:
    def __init__(__self__, *,
                 path: pulumi.Input[_builtins.str],
                 roleid: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 ugid: pulumi.Input[_builtins.str],
                 propagate: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a ACL resource.
        :param pulumi.Input[_builtins.str] path: The path of the ACL.
        :param pulumi.Input[_builtins.str] roleid: The role ID of the ACL.
        :param pulumi.Input[_builtins.str] type: The type of the ACL. Must be one of 'user', 'group', or 'token'.
        :param pulumi.Input[_builtins.str] ugid: The user, group, or token ID associated with the ACL.
        :param pulumi.Input[_builtins.bool] propagate: Whether the ACL should propagate to child objects.
        """
        pulumi.set(__self__, "path", path)
        pulumi.set(__self__, "roleid", roleid)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "ugid", ugid)
        if propagate is not None:
            pulumi.set(__self__, "propagate", propagate)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Input[_builtins.str]:
        """
        The path of the ACL.
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter
    def roleid(self) -> pulumi.Input[_builtins.str]:
        """
        The role ID of the ACL.
        """
        return pulumi.get(self, "roleid")

    @roleid.setter
    def roleid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "roleid", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        The type of the ACL. Must be one of 'user', 'group', or 'token'.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def ugid(self) -> pulumi.Input[_builtins.str]:
        """
        The user, group, or token ID associated with the ACL.
        """
        return pulumi.get(self, "ugid")

    @ugid.setter
    def ugid(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "ugid", value)

    @_builtins.property
    @pulumi.getter
    def propagate(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the ACL should propagate to child objects.
        """
        return pulumi.get(self, "propagate")

    @propagate.setter
    def propagate(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "propagate", value)


@pulumi.type_token("pve:acl:ACL")
class ACL(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 propagate: Optional[pulumi.Input[_builtins.bool]] = None,
                 roleid: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 ugid: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        A Proxmox ACL resource that controls access to Proxmox objects.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] path: The path of the ACL.
        :param pulumi.Input[_builtins.bool] propagate: Whether the ACL should propagate to child objects.
        :param pulumi.Input[_builtins.str] roleid: The role ID of the ACL.
        :param pulumi.Input[_builtins.str] type: The type of the ACL. Must be one of 'user', 'group', or 'token'.
        :param pulumi.Input[_builtins.str] ugid: The user, group, or token ID associated with the ACL.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ACLArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Proxmox ACL resource that controls access to Proxmox objects.

        :param str resource_name: The name of the resource.
        :param ACLArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ACLArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 path: Optional[pulumi.Input[_builtins.str]] = None,
                 propagate: Optional[pulumi.Input[_builtins.bool]] = None,
                 roleid: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 ugid: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ACLArgs.__new__(ACLArgs)

            if path is None and not opts.urn:
                raise TypeError("Missing required property 'path'")
            __props__.__dict__["path"] = path
            __props__.__dict__["propagate"] = propagate
            if roleid is None and not opts.urn:
                raise TypeError("Missing required property 'roleid'")
            __props__.__dict__["roleid"] = roleid
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            if ugid is None and not opts.urn:
                raise TypeError("Missing required property 'ugid'")
            __props__.__dict__["ugid"] = ugid
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["path", "propagate", "roleid", "type", "ugid"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(ACL, __self__).__init__(
            'pve:acl:ACL',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'ACL':
        """
        Get an existing ACL resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ACLArgs.__new__(ACLArgs)

        __props__.__dict__["path"] = None
        __props__.__dict__["propagate"] = None
        __props__.__dict__["roleid"] = None
        __props__.__dict__["type"] = None
        __props__.__dict__["ugid"] = None
        return ACL(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Output[_builtins.str]:
        """
        The path of the ACL.
        """
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter
    def propagate(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the ACL should propagate to child objects.
        """
        return pulumi.get(self, "propagate")

    @_builtins.property
    @pulumi.getter
    def roleid(self) -> pulumi.Output[_builtins.str]:
        """
        The role ID of the ACL.
        """
        return pulumi.get(self, "roleid")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        The type of the ACL. Must be one of 'user', 'group', or 'token'.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def ugid(self) -> pulumi.Output[_builtins.str]:
        """
        The user, group, or token ID associated with the ACL.
        """
        return pulumi.get(self, "ugid")

