// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/hctamu/pulumi-pve/sdk/go/pve/internal"
)

var _ = internal.GetEnvOrDefault

func GetPveToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "pve:pveToken")
}
func GetPveUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "pve:pveUrl")
}
func GetPveUser(ctx *pulumi.Context) string {
	return config.Get(ctx, "pve:pveUser")
}
func GetSshPass(ctx *pulumi.Context) string {
	return config.Get(ctx, "pve:sshPass")
}
func GetSshUser(ctx *pulumi.Context) string {
	return config.Get(ctx, "pve:sshUser")
}
