// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { HaArgs } from "./ha";
export type Ha = import("./ha").Ha;
export const Ha: typeof import("./ha").Ha = null as any;
utilities.lazyLoad(exports, ["Ha"], () => require("./ha"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pve:ha:Ha":
                return new Ha(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pve", "ha", _module)
