// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.hctamu.pve;

import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("pve");
    public Optional<Boolean> insecureSkipVerify() {
        return Codegen.booleanProp("insecureSkipVerify").config(config).get();
    }
    public String pveToken() {
        return Codegen.stringProp("pveToken").config(config).require();
    }
    public String pveUrl() {
        return Codegen.stringProp("pveUrl").config(config).require();
    }
    public String pveUser() {
        return Codegen.stringProp("pveUser").config(config).require();
    }
    public String sshPass() {
        return Codegen.stringProp("sshPass").config(config).require();
    }
    public String sshUser() {
        return Codegen.stringProp("sshUser").config(config).require();
    }
}
