// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sdnapply

import (
	"context"
	"reflect"

	"github.com/hctamu/pulumi-pve/sdk/go/pve/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Applies pending SDN configuration changes in Proxmox VE via PUT /cluster/sdn. Re-runs whenever any trigger value changes.
type SDNApply struct {
	pulumi.CustomResourceState

	// Arbitrary key-value pairs that can include resource outputs or complex objects. When any trigger value changes, the SDN apply is re-executed.
	Triggers pulumi.MapOutput `pulumi:"triggers"`
}

// NewSDNApply registers a new resource with the given unique name, arguments, and options.
func NewSDNApply(ctx *pulumi.Context,
	name string, args *SDNApplyArgs, opts ...pulumi.ResourceOption) (*SDNApply, error) {
	if args == nil {
		args = &SDNApplyArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SDNApply
	err := ctx.RegisterResource("pve:sdnapply:SDNApply", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSDNApply gets an existing SDNApply resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSDNApply(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SDNApplyState, opts ...pulumi.ResourceOption) (*SDNApply, error) {
	var resource SDNApply
	err := ctx.ReadResource("pve:sdnapply:SDNApply", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SDNApply resources.
type sdnapplyState struct {
}

type SDNApplyState struct {
}

func (SDNApplyState) ElementType() reflect.Type {
	return reflect.TypeOf((*sdnapplyState)(nil)).Elem()
}

type sdnapplyArgs struct {
	// Arbitrary key-value pairs that can include resource outputs or complex objects. When any trigger value changes, the SDN apply is re-executed.
	Triggers map[string]interface{} `pulumi:"triggers"`
}

// The set of arguments for constructing a SDNApply resource.
type SDNApplyArgs struct {
	// Arbitrary key-value pairs that can include resource outputs or complex objects. When any trigger value changes, the SDN apply is re-executed.
	Triggers pulumi.MapInput
}

func (SDNApplyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sdnapplyArgs)(nil)).Elem()
}

type SDNApplyInput interface {
	pulumi.Input

	ToSDNApplyOutput() SDNApplyOutput
	ToSDNApplyOutputWithContext(ctx context.Context) SDNApplyOutput
}

func (*SDNApply) ElementType() reflect.Type {
	return reflect.TypeOf((**SDNApply)(nil)).Elem()
}

func (i *SDNApply) ToSDNApplyOutput() SDNApplyOutput {
	return i.ToSDNApplyOutputWithContext(context.Background())
}

func (i *SDNApply) ToSDNApplyOutputWithContext(ctx context.Context) SDNApplyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SDNApplyOutput)
}

// SDNApplyArrayInput is an input type that accepts SDNApplyArray and SDNApplyArrayOutput values.
// You can construct a concrete instance of `SDNApplyArrayInput` via:
//
//	SDNApplyArray{ SDNApplyArgs{...} }
type SDNApplyArrayInput interface {
	pulumi.Input

	ToSDNApplyArrayOutput() SDNApplyArrayOutput
	ToSDNApplyArrayOutputWithContext(context.Context) SDNApplyArrayOutput
}

type SDNApplyArray []SDNApplyInput

func (SDNApplyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SDNApply)(nil)).Elem()
}

func (i SDNApplyArray) ToSDNApplyArrayOutput() SDNApplyArrayOutput {
	return i.ToSDNApplyArrayOutputWithContext(context.Background())
}

func (i SDNApplyArray) ToSDNApplyArrayOutputWithContext(ctx context.Context) SDNApplyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SDNApplyArrayOutput)
}

// SDNApplyMapInput is an input type that accepts SDNApplyMap and SDNApplyMapOutput values.
// You can construct a concrete instance of `SDNApplyMapInput` via:
//
//	SDNApplyMap{ "key": SDNApplyArgs{...} }
type SDNApplyMapInput interface {
	pulumi.Input

	ToSDNApplyMapOutput() SDNApplyMapOutput
	ToSDNApplyMapOutputWithContext(context.Context) SDNApplyMapOutput
}

type SDNApplyMap map[string]SDNApplyInput

func (SDNApplyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SDNApply)(nil)).Elem()
}

func (i SDNApplyMap) ToSDNApplyMapOutput() SDNApplyMapOutput {
	return i.ToSDNApplyMapOutputWithContext(context.Background())
}

func (i SDNApplyMap) ToSDNApplyMapOutputWithContext(ctx context.Context) SDNApplyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SDNApplyMapOutput)
}

type SDNApplyOutput struct{ *pulumi.OutputState }

func (SDNApplyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SDNApply)(nil)).Elem()
}

func (o SDNApplyOutput) ToSDNApplyOutput() SDNApplyOutput {
	return o
}

func (o SDNApplyOutput) ToSDNApplyOutputWithContext(ctx context.Context) SDNApplyOutput {
	return o
}

// Arbitrary key-value pairs that can include resource outputs or complex objects. When any trigger value changes, the SDN apply is re-executed.
func (o SDNApplyOutput) Triggers() pulumi.MapOutput {
	return o.ApplyT(func(v *SDNApply) pulumi.MapOutput { return v.Triggers }).(pulumi.MapOutput)
}

type SDNApplyArrayOutput struct{ *pulumi.OutputState }

func (SDNApplyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SDNApply)(nil)).Elem()
}

func (o SDNApplyArrayOutput) ToSDNApplyArrayOutput() SDNApplyArrayOutput {
	return o
}

func (o SDNApplyArrayOutput) ToSDNApplyArrayOutputWithContext(ctx context.Context) SDNApplyArrayOutput {
	return o
}

func (o SDNApplyArrayOutput) Index(i pulumi.IntInput) SDNApplyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SDNApply {
		return vs[0].([]*SDNApply)[vs[1].(int)]
	}).(SDNApplyOutput)
}

type SDNApplyMapOutput struct{ *pulumi.OutputState }

func (SDNApplyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SDNApply)(nil)).Elem()
}

func (o SDNApplyMapOutput) ToSDNApplyMapOutput() SDNApplyMapOutput {
	return o
}

func (o SDNApplyMapOutput) ToSDNApplyMapOutputWithContext(ctx context.Context) SDNApplyMapOutput {
	return o
}

func (o SDNApplyMapOutput) MapIndex(k pulumi.StringInput) SDNApplyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SDNApply {
		return vs[0].(map[string]*SDNApply)[vs[1].(string)]
	}).(SDNApplyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SDNApplyInput)(nil)).Elem(), &SDNApply{})
	pulumi.RegisterInputType(reflect.TypeOf((*SDNApplyArrayInput)(nil)).Elem(), SDNApplyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SDNApplyMapInput)(nil)).Elem(), SDNApplyMap{})
	pulumi.RegisterOutputType(SDNApplyOutput{})
	pulumi.RegisterOutputType(SDNApplyArrayOutput{})
	pulumi.RegisterOutputType(SDNApplyMapOutput{})
}
