// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Hctamu.Pve.Storage.Outputs
{

    [OutputType]
    public sealed class FileSourceRaw
    {
        /// <summary>
        /// The raw data in []byte
        /// </summary>
        public readonly string FileData;
        /// <summary>
        /// The name of the file
        /// </summary>
        public readonly string FileName;

        [OutputConstructor]
        private FileSourceRaw(
            string fileData,

            string fileName)
        {
            FileData = fileData;
            FileName = fileName;
        }
    }
}
