# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from .. import proxmox as _proxmox

__all__ = ['VMArgs', 'VM']

@pulumi.input_type
class VMArgs:
    def __init__(__self__, *,
                 disks: pulumi.Input[Sequence[pulumi.Input['_proxmox.DiskArgs']]],
                 name: pulumi.Input[_builtins.str],
                 autostart: Optional[pulumi.Input[_builtins.int]] = None,
                 balloon: Optional[pulumi.Input[_builtins.int]] = None,
                 clone: Optional[pulumi.Input['_proxmox.CloneArgs']] = None,
                 cpu: Optional[pulumi.Input['_proxmox.CPUArgs']] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 efidisk: Optional[pulumi.Input['_proxmox.EfiDiskArgs']] = None,
                 hotplug: Optional[pulumi.Input[_builtins.str]] = None,
                 machine: Optional[pulumi.Input[_builtins.str]] = None,
                 memory: Optional[pulumi.Input[_builtins.int]] = None,
                 node: Optional[pulumi.Input[_builtins.str]] = None,
                 ostype: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 template: Optional[pulumi.Input[_builtins.int]] = None,
                 vm_id: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a VM resource.

        :param pulumi.Input[Sequence[pulumi.Input['_proxmox.DiskArgs']]] disks: List of disk configurations attached to the virtual machine.
        :param pulumi.Input[_builtins.str] name: Name of the virtual machine.
        :param pulumi.Input[_builtins.int] autostart: Automatically start the VM when the host boots (1 to enable, 0 to disable).
        :param pulumi.Input[_builtins.int] balloon: Minimum memory for ballooning in megabytes (0 disables the balloon device).
        :param pulumi.Input['_proxmox.CloneArgs'] clone: Clone configuration for creating the VM from a source template or VM.
        :param pulumi.Input['_proxmox.CPUArgs'] cpu: CPU configuration including type, topology, and feature flags.
        :param pulumi.Input[_builtins.str] description: Description or notes for the virtual machine.
        :param pulumi.Input['_proxmox.EfiDiskArgs'] efidisk: EFI disk configuration (required when bios is set to ovmf).
        :param pulumi.Input[_builtins.str] hotplug: Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
        :param pulumi.Input[_builtins.str] machine: Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
        :param pulumi.Input[_builtins.int] memory: Memory size in megabytes.
        :param pulumi.Input[_builtins.str] node: Proxmox node where the VM resides.
        :param pulumi.Input[_builtins.str] ostype: Guest operating system type (e.g., l26, win11, other).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags associated with the virtual machine.
        :param pulumi.Input[_builtins.int] template: Mark the VM as a template (1) or a regular VM (0).
        :param pulumi.Input[_builtins.int] vm_id: Unique numeric identifier for the virtual machine (auto-assigned if omitted).
        """
        pulumi.set(__self__, "disks", disks)
        pulumi.set(__self__, "name", name)
        if autostart is not None:
            pulumi.set(__self__, "autostart", autostart)
        if balloon is not None:
            pulumi.set(__self__, "balloon", balloon)
        if clone is not None:
            pulumi.set(__self__, "clone", clone)
        if cpu is not None:
            pulumi.set(__self__, "cpu", cpu)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if efidisk is not None:
            pulumi.set(__self__, "efidisk", efidisk)
        if hotplug is not None:
            pulumi.set(__self__, "hotplug", hotplug)
        if machine is not None:
            pulumi.set(__self__, "machine", machine)
        if memory is not None:
            pulumi.set(__self__, "memory", memory)
        if node is not None:
            pulumi.set(__self__, "node", node)
        if ostype is not None:
            pulumi.set(__self__, "ostype", ostype)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if template is not None:
            pulumi.set(__self__, "template", template)
        if vm_id is not None:
            pulumi.set(__self__, "vm_id", vm_id)

    @_builtins.property
    @pulumi.getter
    def disks(self) -> pulumi.Input[Sequence[pulumi.Input['_proxmox.DiskArgs']]]:
        """
        List of disk configurations attached to the virtual machine.
        """
        return pulumi.get(self, "disks")

    @disks.setter
    def disks(self, value: pulumi.Input[Sequence[pulumi.Input['_proxmox.DiskArgs']]]):
        pulumi.set(self, "disks", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the virtual machine.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def autostart(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Automatically start the VM when the host boots (1 to enable, 0 to disable).
        """
        return pulumi.get(self, "autostart")

    @autostart.setter
    def autostart(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "autostart", value)

    @_builtins.property
    @pulumi.getter
    def balloon(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minimum memory for ballooning in megabytes (0 disables the balloon device).
        """
        return pulumi.get(self, "balloon")

    @balloon.setter
    def balloon(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "balloon", value)

    @_builtins.property
    @pulumi.getter
    def clone(self) -> Optional[pulumi.Input['_proxmox.CloneArgs']]:
        """
        Clone configuration for creating the VM from a source template or VM.
        """
        return pulumi.get(self, "clone")

    @clone.setter
    def clone(self, value: Optional[pulumi.Input['_proxmox.CloneArgs']]):
        pulumi.set(self, "clone", value)

    @_builtins.property
    @pulumi.getter
    def cpu(self) -> Optional[pulumi.Input['_proxmox.CPUArgs']]:
        """
        CPU configuration including type, topology, and feature flags.
        """
        return pulumi.get(self, "cpu")

    @cpu.setter
    def cpu(self, value: Optional[pulumi.Input['_proxmox.CPUArgs']]):
        pulumi.set(self, "cpu", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description or notes for the virtual machine.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def efidisk(self) -> Optional[pulumi.Input['_proxmox.EfiDiskArgs']]:
        """
        EFI disk configuration (required when bios is set to ovmf).
        """
        return pulumi.get(self, "efidisk")

    @efidisk.setter
    def efidisk(self, value: Optional[pulumi.Input['_proxmox.EfiDiskArgs']]):
        pulumi.set(self, "efidisk", value)

    @_builtins.property
    @pulumi.getter
    def hotplug(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
        """
        return pulumi.get(self, "hotplug")

    @hotplug.setter
    def hotplug(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "hotplug", value)

    @_builtins.property
    @pulumi.getter
    def machine(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
        """
        return pulumi.get(self, "machine")

    @machine.setter
    def machine(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "machine", value)

    @_builtins.property
    @pulumi.getter
    def memory(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Memory size in megabytes.
        """
        return pulumi.get(self, "memory")

    @memory.setter
    def memory(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "memory", value)

    @_builtins.property
    @pulumi.getter
    def node(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Proxmox node where the VM resides.
        """
        return pulumi.get(self, "node")

    @node.setter
    def node(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "node", value)

    @_builtins.property
    @pulumi.getter
    def ostype(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Guest operating system type (e.g., l26, win11, other).
        """
        return pulumi.get(self, "ostype")

    @ostype.setter
    def ostype(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ostype", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Tags associated with the virtual machine.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def template(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Mark the VM as a template (1) or a regular VM (0).
        """
        return pulumi.get(self, "template")

    @template.setter
    def template(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "template", value)

    @_builtins.property
    @pulumi.getter(name="vmId")
    def vm_id(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Unique numeric identifier for the virtual machine (auto-assigned if omitted).
        """
        return pulumi.get(self, "vm_id")

    @vm_id.setter
    def vm_id(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "vm_id", value)


@pulumi.type_token("pve:vm:VM")
class VM(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 autostart: Optional[pulumi.Input[_builtins.int]] = None,
                 balloon: Optional[pulumi.Input[_builtins.int]] = None,
                 clone: Optional[pulumi.Input[Union['_proxmox.CloneArgs', '_proxmox.CloneArgsDict']]] = None,
                 cpu: Optional[pulumi.Input[Union['_proxmox.CPUArgs', '_proxmox.CPUArgsDict']]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['_proxmox.DiskArgs', '_proxmox.DiskArgsDict']]]]] = None,
                 efidisk: Optional[pulumi.Input[Union['_proxmox.EfiDiskArgs', '_proxmox.EfiDiskArgsDict']]] = None,
                 hotplug: Optional[pulumi.Input[_builtins.str]] = None,
                 machine: Optional[pulumi.Input[_builtins.str]] = None,
                 memory: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 node: Optional[pulumi.Input[_builtins.str]] = None,
                 ostype: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 template: Optional[pulumi.Input[_builtins.int]] = None,
                 vm_id: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        Create a VM resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] autostart: Automatically start the VM when the host boots (1 to enable, 0 to disable).
        :param pulumi.Input[_builtins.int] balloon: Minimum memory for ballooning in megabytes (0 disables the balloon device).
        :param pulumi.Input[Union['_proxmox.CloneArgs', '_proxmox.CloneArgsDict']] clone: Clone configuration for creating the VM from a source template or VM.
        :param pulumi.Input[Union['_proxmox.CPUArgs', '_proxmox.CPUArgsDict']] cpu: CPU configuration including type, topology, and feature flags.
        :param pulumi.Input[_builtins.str] description: Description or notes for the virtual machine.
        :param pulumi.Input[Sequence[pulumi.Input[Union['_proxmox.DiskArgs', '_proxmox.DiskArgsDict']]]] disks: List of disk configurations attached to the virtual machine.
        :param pulumi.Input[Union['_proxmox.EfiDiskArgs', '_proxmox.EfiDiskArgsDict']] efidisk: EFI disk configuration (required when bios is set to ovmf).
        :param pulumi.Input[_builtins.str] hotplug: Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
        :param pulumi.Input[_builtins.str] machine: Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
        :param pulumi.Input[_builtins.int] memory: Memory size in megabytes.
        :param pulumi.Input[_builtins.str] name: Name of the virtual machine.
        :param pulumi.Input[_builtins.str] node: Proxmox node where the VM resides.
        :param pulumi.Input[_builtins.str] ostype: Guest operating system type (e.g., l26, win11, other).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags associated with the virtual machine.
        :param pulumi.Input[_builtins.int] template: Mark the VM as a template (1) or a regular VM (0).
        :param pulumi.Input[_builtins.int] vm_id: Unique numeric identifier for the virtual machine (auto-assigned if omitted).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VMArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a VM resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param VMArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VMArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 autostart: Optional[pulumi.Input[_builtins.int]] = None,
                 balloon: Optional[pulumi.Input[_builtins.int]] = None,
                 clone: Optional[pulumi.Input[Union['_proxmox.CloneArgs', '_proxmox.CloneArgsDict']]] = None,
                 cpu: Optional[pulumi.Input[Union['_proxmox.CPUArgs', '_proxmox.CPUArgsDict']]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 disks: Optional[pulumi.Input[Sequence[pulumi.Input[Union['_proxmox.DiskArgs', '_proxmox.DiskArgsDict']]]]] = None,
                 efidisk: Optional[pulumi.Input[Union['_proxmox.EfiDiskArgs', '_proxmox.EfiDiskArgsDict']]] = None,
                 hotplug: Optional[pulumi.Input[_builtins.str]] = None,
                 machine: Optional[pulumi.Input[_builtins.str]] = None,
                 memory: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 node: Optional[pulumi.Input[_builtins.str]] = None,
                 ostype: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 template: Optional[pulumi.Input[_builtins.int]] = None,
                 vm_id: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VMArgs.__new__(VMArgs)

            __props__.__dict__["autostart"] = autostart
            __props__.__dict__["balloon"] = balloon
            __props__.__dict__["clone"] = clone
            __props__.__dict__["cpu"] = cpu
            __props__.__dict__["description"] = description
            if disks is None and not opts.urn:
                raise TypeError("Missing required property 'disks'")
            __props__.__dict__["disks"] = disks
            __props__.__dict__["efidisk"] = efidisk
            __props__.__dict__["hotplug"] = hotplug
            __props__.__dict__["machine"] = machine
            __props__.__dict__["memory"] = memory
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["node"] = node
            __props__.__dict__["ostype"] = ostype
            __props__.__dict__["tags"] = tags
            __props__.__dict__["template"] = template
            __props__.__dict__["vm_id"] = vm_id
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["vmId"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(VM, __self__).__init__(
            'pve:vm:VM',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'VM':
        """
        Get an existing VM resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = VMArgs.__new__(VMArgs)

        __props__.__dict__["autostart"] = None
        __props__.__dict__["balloon"] = None
        __props__.__dict__["clone"] = None
        __props__.__dict__["cpu"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["disks"] = None
        __props__.__dict__["efidisk"] = None
        __props__.__dict__["hotplug"] = None
        __props__.__dict__["machine"] = None
        __props__.__dict__["memory"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["node"] = None
        __props__.__dict__["ostype"] = None
        __props__.__dict__["tags"] = None
        __props__.__dict__["template"] = None
        __props__.__dict__["vm_id"] = None
        return VM(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def autostart(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Automatically start the VM when the host boots (1 to enable, 0 to disable).
        """
        return pulumi.get(self, "autostart")

    @_builtins.property
    @pulumi.getter
    def balloon(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Minimum memory for ballooning in megabytes (0 disables the balloon device).
        """
        return pulumi.get(self, "balloon")

    @_builtins.property
    @pulumi.getter
    def clone(self) -> pulumi.Output[Optional['_proxmox.outputs.Clone']]:
        """
        Clone configuration for creating the VM from a source template or VM.
        """
        return pulumi.get(self, "clone")

    @_builtins.property
    @pulumi.getter
    def cpu(self) -> pulumi.Output[Optional['_proxmox.outputs.CPU']]:
        """
        CPU configuration including type, topology, and feature flags.
        """
        return pulumi.get(self, "cpu")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description or notes for the virtual machine.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def disks(self) -> pulumi.Output[Sequence['_proxmox.outputs.Disk']]:
        """
        List of disk configurations attached to the virtual machine.
        """
        return pulumi.get(self, "disks")

    @_builtins.property
    @pulumi.getter
    def efidisk(self) -> pulumi.Output[Optional['_proxmox.outputs.EfiDisk']]:
        """
        EFI disk configuration (required when bios is set to ovmf).
        """
        return pulumi.get(self, "efidisk")

    @_builtins.property
    @pulumi.getter
    def hotplug(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Comma-separated list of hotplug features (network, disk, cpu, memory, usb).
        """
        return pulumi.get(self, "hotplug")

    @_builtins.property
    @pulumi.getter
    def machine(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Machine type for the VM (e.g., pc, q35, pc-i440fx-8.1).
        """
        return pulumi.get(self, "machine")

    @_builtins.property
    @pulumi.getter
    def memory(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Memory size in megabytes.
        """
        return pulumi.get(self, "memory")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the virtual machine.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def node(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Proxmox node where the VM resides.
        """
        return pulumi.get(self, "node")

    @_builtins.property
    @pulumi.getter
    def ostype(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Guest operating system type (e.g., l26, win11, other).
        """
        return pulumi.get(self, "ostype")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Tags associated with the virtual machine.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def template(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Mark the VM as a template (1) or a regular VM (0).
        """
        return pulumi.get(self, "template")

    @_builtins.property
    @pulumi.getter(name="vmId")
    def vm_id(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Unique numeric identifier for the virtual machine (auto-assigned if omitted).
        """
        return pulumi.get(self, "vm_id")

