# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'CPU',
    'Clone',
    'Disk',
    'DiskBandwidth',
    'EfiDisk',
    'FileSourceRaw',
    'NumaNode',
]

@pulumi.output_type
class CPU(dict):
    """
    CPU configuration for the virtual machine.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "flagsDisabled":
            suggest = "flags_disabled"
        elif key == "flagsEnabled":
            suggest = "flags_enabled"
        elif key == "hvVendorId":
            suggest = "hv_vendor_id"
        elif key == "numaNodes":
            suggest = "numa_nodes"
        elif key == "physBits":
            suggest = "phys_bits"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in CPU. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        CPU.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        CPU.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 cores: Optional[_builtins.int] = None,
                 flags_disabled: Optional[Sequence[_builtins.str]] = None,
                 flags_enabled: Optional[Sequence[_builtins.str]] = None,
                 hidden: Optional[_builtins.bool] = None,
                 hv_vendor_id: Optional[_builtins.str] = None,
                 limit: Optional[_builtins.float] = None,
                 numa: Optional[_builtins.bool] = None,
                 numa_nodes: Optional[Sequence['outputs.NumaNode']] = None,
                 phys_bits: Optional[_builtins.str] = None,
                 sockets: Optional[_builtins.int] = None,
                 type: Optional[_builtins.str] = None,
                 units: Optional[_builtins.int] = None,
                 vcpus: Optional[_builtins.int] = None):
        """
        CPU configuration for the virtual machine.

        :param _builtins.int cores: Number of CPU cores per socket.
        :param Sequence[_builtins.str] flags_disabled: List of CPU flags to disable.
        :param Sequence[_builtins.str] flags_enabled: List of CPU flags to enable (e.g., pcid, spec-ctrl).
        :param _builtins.bool hidden: Hide VM CPU type from the guest operating system.
        :param _builtins.str hv_vendor_id: Hyper-V vendor ID presented to the guest (up to 12 characters).
        :param _builtins.float limit: CPU usage limit as a fraction of one core (e.g., 1.5 caps at 150%).
        :param _builtins.bool numa: Enable NUMA topology.
        :param Sequence['NumaNode'] numa_nodes: NUMA node topology configuration.
        :param _builtins.str phys_bits: Number of physical address bits exposed to the guest (e.g., 36, 40, 48).
        :param _builtins.int sockets: Number of CPU sockets.
        :param _builtins.str type: CPU type (e.g., host, kvm64, x86-64-v2-AES).
        :param _builtins.int units: CPU weight for the scheduler relative to other VMs (higher = more CPU time).
        :param _builtins.int vcpus: Number of hotplugged vCPUs (must be <= cores * sockets).
        """
        if cores is None:
            cores = 1
        if cores is not None:
            pulumi.set(__self__, "cores", cores)
        if flags_disabled is not None:
            pulumi.set(__self__, "flags_disabled", flags_disabled)
        if flags_enabled is not None:
            pulumi.set(__self__, "flags_enabled", flags_enabled)
        if hidden is not None:
            pulumi.set(__self__, "hidden", hidden)
        if hv_vendor_id is not None:
            pulumi.set(__self__, "hv_vendor_id", hv_vendor_id)
        if limit is not None:
            pulumi.set(__self__, "limit", limit)
        if numa is not None:
            pulumi.set(__self__, "numa", numa)
        if numa_nodes is not None:
            pulumi.set(__self__, "numa_nodes", numa_nodes)
        if phys_bits is not None:
            pulumi.set(__self__, "phys_bits", phys_bits)
        if sockets is None:
            sockets = 1
        if sockets is not None:
            pulumi.set(__self__, "sockets", sockets)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if units is not None:
            pulumi.set(__self__, "units", units)
        if vcpus is not None:
            pulumi.set(__self__, "vcpus", vcpus)

    @_builtins.property
    @pulumi.getter
    def cores(self) -> Optional[_builtins.int]:
        """
        Number of CPU cores per socket.
        """
        return pulumi.get(self, "cores")

    @_builtins.property
    @pulumi.getter(name="flagsDisabled")
    def flags_disabled(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of CPU flags to disable.
        """
        return pulumi.get(self, "flags_disabled")

    @_builtins.property
    @pulumi.getter(name="flagsEnabled")
    def flags_enabled(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of CPU flags to enable (e.g., pcid, spec-ctrl).
        """
        return pulumi.get(self, "flags_enabled")

    @_builtins.property
    @pulumi.getter
    def hidden(self) -> Optional[_builtins.bool]:
        """
        Hide VM CPU type from the guest operating system.
        """
        return pulumi.get(self, "hidden")

    @_builtins.property
    @pulumi.getter(name="hvVendorId")
    def hv_vendor_id(self) -> Optional[_builtins.str]:
        """
        Hyper-V vendor ID presented to the guest (up to 12 characters).
        """
        return pulumi.get(self, "hv_vendor_id")

    @_builtins.property
    @pulumi.getter
    def limit(self) -> Optional[_builtins.float]:
        """
        CPU usage limit as a fraction of one core (e.g., 1.5 caps at 150%).
        """
        return pulumi.get(self, "limit")

    @_builtins.property
    @pulumi.getter
    def numa(self) -> Optional[_builtins.bool]:
        """
        Enable NUMA topology.
        """
        return pulumi.get(self, "numa")

    @_builtins.property
    @pulumi.getter(name="numaNodes")
    def numa_nodes(self) -> Optional[Sequence['outputs.NumaNode']]:
        """
        NUMA node topology configuration.
        """
        return pulumi.get(self, "numa_nodes")

    @_builtins.property
    @pulumi.getter(name="physBits")
    def phys_bits(self) -> Optional[_builtins.str]:
        """
        Number of physical address bits exposed to the guest (e.g., 36, 40, 48).
        """
        return pulumi.get(self, "phys_bits")

    @_builtins.property
    @pulumi.getter
    def sockets(self) -> Optional[_builtins.int]:
        """
        Number of CPU sockets.
        """
        return pulumi.get(self, "sockets")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        CPU type (e.g., host, kvm64, x86-64-v2-AES).
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def units(self) -> Optional[_builtins.int]:
        """
        CPU weight for the scheduler relative to other VMs (higher = more CPU time).
        """
        return pulumi.get(self, "units")

    @_builtins.property
    @pulumi.getter
    def vcpus(self) -> Optional[_builtins.int]:
        """
        Number of hotplugged vCPUs (must be <= cores * sockets).
        """
        return pulumi.get(self, "vcpus")


@pulumi.output_type
class Clone(dict):
    """
    Configuration for cloning a source virtual machine.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "vmId":
            suggest = "vm_id"
        elif key == "dataStoreId":
            suggest = "data_store_id"
        elif key == "fullClone":
            suggest = "full_clone"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Clone. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Clone.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Clone.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 vm_id: _builtins.int,
                 data_store_id: Optional[_builtins.str] = None,
                 full_clone: Optional[_builtins.bool] = None,
                 node: Optional[_builtins.str] = None,
                 timeout: Optional[_builtins.int] = None):
        """
        Configuration for cloning a source virtual machine.

        :param _builtins.int vm_id: Source VM ID to clone from.
        :param _builtins.str data_store_id: Target storage pool for the cloned disks.
        :param _builtins.bool full_clone: Create a full independent clone instead of a linked clone.
        :param _builtins.str node: Target Proxmox node for the clone operation.
        :param _builtins.int timeout: Timeout in seconds for the clone operation.
        """
        pulumi.set(__self__, "vm_id", vm_id)
        if data_store_id is not None:
            pulumi.set(__self__, "data_store_id", data_store_id)
        if full_clone is not None:
            pulumi.set(__self__, "full_clone", full_clone)
        if node is not None:
            pulumi.set(__self__, "node", node)
        if timeout is not None:
            pulumi.set(__self__, "timeout", timeout)

    @_builtins.property
    @pulumi.getter(name="vmId")
    def vm_id(self) -> _builtins.int:
        """
        Source VM ID to clone from.
        """
        return pulumi.get(self, "vm_id")

    @_builtins.property
    @pulumi.getter(name="dataStoreId")
    def data_store_id(self) -> Optional[_builtins.str]:
        """
        Target storage pool for the cloned disks.
        """
        return pulumi.get(self, "data_store_id")

    @_builtins.property
    @pulumi.getter(name="fullClone")
    def full_clone(self) -> Optional[_builtins.bool]:
        """
        Create a full independent clone instead of a linked clone.
        """
        return pulumi.get(self, "full_clone")

    @_builtins.property
    @pulumi.getter
    def node(self) -> Optional[_builtins.str]:
        """
        Target Proxmox node for the clone operation.
        """
        return pulumi.get(self, "node")

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> Optional[_builtins.int]:
        """
        Timeout in seconds for the clone operation.
        """
        return pulumi.get(self, "timeout")


@pulumi.output_type
class Disk(dict):
    """
    Disk configuration for the virtual machine.
    """
    def __init__(__self__, *,
                 interface: _builtins.str,
                 size: _builtins.int,
                 storage: _builtins.str,
                 aio: Optional[_builtins.str] = None,
                 backup: Optional[_builtins.bool] = None,
                 bandwidth: Optional['outputs.DiskBandwidth'] = None,
                 cache: Optional[_builtins.str] = None,
                 discard: Optional[_builtins.str] = None,
                 filename: Optional[_builtins.str] = None,
                 format: Optional[_builtins.str] = None,
                 iothread: Optional[_builtins.bool] = None,
                 media: Optional[_builtins.str] = None,
                 queues: Optional[_builtins.int] = None,
                 replicate: Optional[_builtins.bool] = None,
                 rerror: Optional[_builtins.str] = None,
                 ro: Optional[_builtins.bool] = None,
                 scsiblock: Optional[_builtins.bool] = None,
                 serial: Optional[_builtins.str] = None,
                 shared: Optional[_builtins.bool] = None,
                 snapshot: Optional[_builtins.bool] = None,
                 ssd: Optional[_builtins.bool] = None,
                 werror: Optional[_builtins.str] = None,
                 wwn: Optional[_builtins.str] = None):
        """
        Disk configuration for the virtual machine.

        :param _builtins.str interface: Disk interface type and slot (e.g., scsi0, virtio0, ide1, sata2). This field is the stable identity key for the disk: changing it is treated as removing the old disk (permanently deleting the image) and adding a new empty disk. To move data between slots, perform the migration manually in Proxmox.
        :param _builtins.int size: Disk size in gigabytes.
        :param _builtins.str storage: Target storage pool for the disk (e.g., local-lvm, ceph-pool).
        :param _builtins.str aio: Asynchronous I/O mode: native, threads, or io_uring. Omit to use the Proxmox default.
        :param _builtins.bool backup: Include this disk in Proxmox backups. Defaults to true when omitted; set to false to exclude the disk from backups.
        :param 'DiskBandwidth' bandwidth: I/O throttle limits for this disk (Proxmox GUI 'Bandwidth' section). Omit to apply no throttling.
        :param _builtins.str cache: Cache mode for the disk: none, writethrough, writeback, unsafe, or directsync. Omit to use the Proxmox default (no explicit cache setting).
        :param _builtins.str discard: Discard/TRIM support: ignore (default) or on. Enable for thin-provisioned storage and SSDs to reclaim freed blocks.
        :param _builtins.str filename: File name of the disk image (computed by Proxmox if not provided).
        :param _builtins.str format: Disk image format: raw, qcow2, vmdk, etc. Relevant primarily for file-based storage (local, NFS); block-based storage (LVM, Ceph) ignores this field and may not return it on read. Changing the format of an existing disk is not supported by Proxmox.
        :param _builtins.bool iothread: Enable a dedicated I/O thread for this disk. Only supported on scsi and virtio interfaces.
        :param _builtins.str media: Media type: 'disk' (default) or 'cdrom'. Supported on all disk interfaces.
        :param _builtins.int queues: Number of I/O queues for this disk. Only supported on scsi and virtio interfaces. Minimum value is 2 (enforced by Proxmox); there is no enforced upper bound.
        :param _builtins.bool replicate: Include this disk in Proxmox storage replication. Defaults to true when omitted; set to false to exclude the disk from replication.
        :param _builtins.str rerror: Action on read I/O errors: 'ignore', 'report', or 'stop'. Proxmox default is 'report'. Supported on all disk interfaces.
        :param _builtins.bool ro: Mount this disk as read-only inside the guest. Only supported on scsi and virtio interfaces.
        :param _builtins.bool scsiblock: Use the scsi-block I/O path instead of virtio-scsi. Only supported on scsi interfaces. May improve performance for some workloads.
        :param _builtins.str serial: Serial number string exposed to the guest OS. Up to 60 characters; alphanumeric characters, hyphens, underscores, and dots are accepted. Commas and equals signs are rejected by Proxmox. Validated and enforced by the provider.
        :param _builtins.bool shared: Mark this disk as shared across cluster nodes. Required for live migration with local storage.
        :param _builtins.bool snapshot: Disk is part of a Proxmox snapshot chain. This field is normally managed by Proxmox and should not be set manually.
        :param _builtins.bool ssd: Emulate a solid-state drive for the guest OS (affects rotation rate hints). Supported on ide, sata, and scsi interfaces; not valid for virtio.
        :param _builtins.str werror: Action on write I/O errors: 'enospc', 'ignore', 'report', or 'stop'. Proxmox default is 'enospc'. Supported on all disk interfaces.
        :param _builtins.str wwn: World Wide Name (unique disk identifier). Must be exactly 16 lowercase hex digits prefixed with '0x', e.g. 0x500a0000deadbeef. Proxmox enforces the format with a regex; invalid values are rejected at apply time.
        """
        pulumi.set(__self__, "interface", interface)
        pulumi.set(__self__, "size", size)
        pulumi.set(__self__, "storage", storage)
        if aio is not None:
            pulumi.set(__self__, "aio", aio)
        if backup is not None:
            pulumi.set(__self__, "backup", backup)
        if bandwidth is not None:
            pulumi.set(__self__, "bandwidth", bandwidth)
        if cache is not None:
            pulumi.set(__self__, "cache", cache)
        if discard is not None:
            pulumi.set(__self__, "discard", discard)
        if filename is not None:
            pulumi.set(__self__, "filename", filename)
        if format is not None:
            pulumi.set(__self__, "format", format)
        if iothread is not None:
            pulumi.set(__self__, "iothread", iothread)
        if media is not None:
            pulumi.set(__self__, "media", media)
        if queues is not None:
            pulumi.set(__self__, "queues", queues)
        if replicate is not None:
            pulumi.set(__self__, "replicate", replicate)
        if rerror is not None:
            pulumi.set(__self__, "rerror", rerror)
        if ro is not None:
            pulumi.set(__self__, "ro", ro)
        if scsiblock is not None:
            pulumi.set(__self__, "scsiblock", scsiblock)
        if serial is not None:
            pulumi.set(__self__, "serial", serial)
        if shared is not None:
            pulumi.set(__self__, "shared", shared)
        if snapshot is not None:
            pulumi.set(__self__, "snapshot", snapshot)
        if ssd is not None:
            pulumi.set(__self__, "ssd", ssd)
        if werror is not None:
            pulumi.set(__self__, "werror", werror)
        if wwn is not None:
            pulumi.set(__self__, "wwn", wwn)

    @_builtins.property
    @pulumi.getter
    def interface(self) -> _builtins.str:
        """
        Disk interface type and slot (e.g., scsi0, virtio0, ide1, sata2). This field is the stable identity key for the disk: changing it is treated as removing the old disk (permanently deleting the image) and adding a new empty disk. To move data between slots, perform the migration manually in Proxmox.
        """
        return pulumi.get(self, "interface")

    @_builtins.property
    @pulumi.getter
    def size(self) -> _builtins.int:
        """
        Disk size in gigabytes.
        """
        return pulumi.get(self, "size")

    @_builtins.property
    @pulumi.getter
    def storage(self) -> _builtins.str:
        """
        Target storage pool for the disk (e.g., local-lvm, ceph-pool).
        """
        return pulumi.get(self, "storage")

    @_builtins.property
    @pulumi.getter
    def aio(self) -> Optional[_builtins.str]:
        """
        Asynchronous I/O mode: native, threads, or io_uring. Omit to use the Proxmox default.
        """
        return pulumi.get(self, "aio")

    @_builtins.property
    @pulumi.getter
    def backup(self) -> Optional[_builtins.bool]:
        """
        Include this disk in Proxmox backups. Defaults to true when omitted; set to false to exclude the disk from backups.
        """
        return pulumi.get(self, "backup")

    @_builtins.property
    @pulumi.getter
    def bandwidth(self) -> Optional['outputs.DiskBandwidth']:
        """
        I/O throttle limits for this disk (Proxmox GUI 'Bandwidth' section). Omit to apply no throttling.
        """
        return pulumi.get(self, "bandwidth")

    @_builtins.property
    @pulumi.getter
    def cache(self) -> Optional[_builtins.str]:
        """
        Cache mode for the disk: none, writethrough, writeback, unsafe, or directsync. Omit to use the Proxmox default (no explicit cache setting).
        """
        return pulumi.get(self, "cache")

    @_builtins.property
    @pulumi.getter
    def discard(self) -> Optional[_builtins.str]:
        """
        Discard/TRIM support: ignore (default) or on. Enable for thin-provisioned storage and SSDs to reclaim freed blocks.
        """
        return pulumi.get(self, "discard")

    @_builtins.property
    @pulumi.getter
    def filename(self) -> Optional[_builtins.str]:
        """
        File name of the disk image (computed by Proxmox if not provided).
        """
        return pulumi.get(self, "filename")

    @_builtins.property
    @pulumi.getter
    def format(self) -> Optional[_builtins.str]:
        """
        Disk image format: raw, qcow2, vmdk, etc. Relevant primarily for file-based storage (local, NFS); block-based storage (LVM, Ceph) ignores this field and may not return it on read. Changing the format of an existing disk is not supported by Proxmox.
        """
        return pulumi.get(self, "format")

    @_builtins.property
    @pulumi.getter
    def iothread(self) -> Optional[_builtins.bool]:
        """
        Enable a dedicated I/O thread for this disk. Only supported on scsi and virtio interfaces.
        """
        return pulumi.get(self, "iothread")

    @_builtins.property
    @pulumi.getter
    def media(self) -> Optional[_builtins.str]:
        """
        Media type: 'disk' (default) or 'cdrom'. Supported on all disk interfaces.
        """
        return pulumi.get(self, "media")

    @_builtins.property
    @pulumi.getter
    def queues(self) -> Optional[_builtins.int]:
        """
        Number of I/O queues for this disk. Only supported on scsi and virtio interfaces. Minimum value is 2 (enforced by Proxmox); there is no enforced upper bound.
        """
        return pulumi.get(self, "queues")

    @_builtins.property
    @pulumi.getter
    def replicate(self) -> Optional[_builtins.bool]:
        """
        Include this disk in Proxmox storage replication. Defaults to true when omitted; set to false to exclude the disk from replication.
        """
        return pulumi.get(self, "replicate")

    @_builtins.property
    @pulumi.getter
    def rerror(self) -> Optional[_builtins.str]:
        """
        Action on read I/O errors: 'ignore', 'report', or 'stop'. Proxmox default is 'report'. Supported on all disk interfaces.
        """
        return pulumi.get(self, "rerror")

    @_builtins.property
    @pulumi.getter
    def ro(self) -> Optional[_builtins.bool]:
        """
        Mount this disk as read-only inside the guest. Only supported on scsi and virtio interfaces.
        """
        return pulumi.get(self, "ro")

    @_builtins.property
    @pulumi.getter
    def scsiblock(self) -> Optional[_builtins.bool]:
        """
        Use the scsi-block I/O path instead of virtio-scsi. Only supported on scsi interfaces. May improve performance for some workloads.
        """
        return pulumi.get(self, "scsiblock")

    @_builtins.property
    @pulumi.getter
    def serial(self) -> Optional[_builtins.str]:
        """
        Serial number string exposed to the guest OS. Up to 60 characters; alphanumeric characters, hyphens, underscores, and dots are accepted. Commas and equals signs are rejected by Proxmox. Validated and enforced by the provider.
        """
        return pulumi.get(self, "serial")

    @_builtins.property
    @pulumi.getter
    def shared(self) -> Optional[_builtins.bool]:
        """
        Mark this disk as shared across cluster nodes. Required for live migration with local storage.
        """
        return pulumi.get(self, "shared")

    @_builtins.property
    @pulumi.getter
    def snapshot(self) -> Optional[_builtins.bool]:
        """
        Disk is part of a Proxmox snapshot chain. This field is normally managed by Proxmox and should not be set manually.
        """
        return pulumi.get(self, "snapshot")

    @_builtins.property
    @pulumi.getter
    def ssd(self) -> Optional[_builtins.bool]:
        """
        Emulate a solid-state drive for the guest OS (affects rotation rate hints). Supported on ide, sata, and scsi interfaces; not valid for virtio.
        """
        return pulumi.get(self, "ssd")

    @_builtins.property
    @pulumi.getter
    def werror(self) -> Optional[_builtins.str]:
        """
        Action on write I/O errors: 'enospc', 'ignore', 'report', or 'stop'. Proxmox default is 'enospc'. Supported on all disk interfaces.
        """
        return pulumi.get(self, "werror")

    @_builtins.property
    @pulumi.getter
    def wwn(self) -> Optional[_builtins.str]:
        """
        World Wide Name (unique disk identifier). Must be exactly 16 lowercase hex digits prefixed with '0x', e.g. 0x500a0000deadbeef. Proxmox enforces the format with a regex; invalid values are rejected at apply time.
        """
        return pulumi.get(self, "wwn")


@pulumi.output_type
class DiskBandwidth(dict):
    """
    I/O throttle limits for the disk
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "iopsRd":
            suggest = "iops_rd"
        elif key == "iopsRdMax":
            suggest = "iops_rd_max"
        elif key == "iopsWr":
            suggest = "iops_wr"
        elif key == "iopsWrMax":
            suggest = "iops_wr_max"
        elif key == "mbpsRd":
            suggest = "mbps_rd"
        elif key == "mbpsRdMax":
            suggest = "mbps_rd_max"
        elif key == "mbpsWr":
            suggest = "mbps_wr"
        elif key == "mbpsWrMax":
            suggest = "mbps_wr_max"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in DiskBandwidth. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        DiskBandwidth.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        DiskBandwidth.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 iops_rd: Optional[_builtins.int] = None,
                 iops_rd_max: Optional[_builtins.int] = None,
                 iops_wr: Optional[_builtins.int] = None,
                 iops_wr_max: Optional[_builtins.int] = None,
                 mbps_rd: Optional[_builtins.float] = None,
                 mbps_rd_max: Optional[_builtins.float] = None,
                 mbps_wr: Optional[_builtins.float] = None,
                 mbps_wr_max: Optional[_builtins.float] = None):
        """
        I/O throttle limits for the disk

        :param _builtins.int iops_rd: Read I/O operations per second limit (0 = unlimited).
        :param _builtins.int iops_rd_max: Read burst I/O operations per second limit.
        :param _builtins.int iops_wr: Write I/O operations per second limit (0 = unlimited).
        :param _builtins.int iops_wr_max: Write burst I/O operations per second limit.
        :param _builtins.float mbps_rd: Read throughput limit in MB/s (0 = unlimited).
        :param _builtins.float mbps_rd_max: Read burst throughput limit in MB/s; allows temporary bursts above MBpsRd.
        :param _builtins.float mbps_wr: Write throughput limit in MB/s (0 = unlimited).
        :param _builtins.float mbps_wr_max: Write burst throughput limit in MB/s; allows temporary bursts above MBpsWr.
        """
        if iops_rd is not None:
            pulumi.set(__self__, "iops_rd", iops_rd)
        if iops_rd_max is not None:
            pulumi.set(__self__, "iops_rd_max", iops_rd_max)
        if iops_wr is not None:
            pulumi.set(__self__, "iops_wr", iops_wr)
        if iops_wr_max is not None:
            pulumi.set(__self__, "iops_wr_max", iops_wr_max)
        if mbps_rd is not None:
            pulumi.set(__self__, "mbps_rd", mbps_rd)
        if mbps_rd_max is not None:
            pulumi.set(__self__, "mbps_rd_max", mbps_rd_max)
        if mbps_wr is not None:
            pulumi.set(__self__, "mbps_wr", mbps_wr)
        if mbps_wr_max is not None:
            pulumi.set(__self__, "mbps_wr_max", mbps_wr_max)

    @_builtins.property
    @pulumi.getter(name="iopsRd")
    def iops_rd(self) -> Optional[_builtins.int]:
        """
        Read I/O operations per second limit (0 = unlimited).
        """
        return pulumi.get(self, "iops_rd")

    @_builtins.property
    @pulumi.getter(name="iopsRdMax")
    def iops_rd_max(self) -> Optional[_builtins.int]:
        """
        Read burst I/O operations per second limit.
        """
        return pulumi.get(self, "iops_rd_max")

    @_builtins.property
    @pulumi.getter(name="iopsWr")
    def iops_wr(self) -> Optional[_builtins.int]:
        """
        Write I/O operations per second limit (0 = unlimited).
        """
        return pulumi.get(self, "iops_wr")

    @_builtins.property
    @pulumi.getter(name="iopsWrMax")
    def iops_wr_max(self) -> Optional[_builtins.int]:
        """
        Write burst I/O operations per second limit.
        """
        return pulumi.get(self, "iops_wr_max")

    @_builtins.property
    @pulumi.getter(name="mbpsRd")
    def mbps_rd(self) -> Optional[_builtins.float]:
        """
        Read throughput limit in MB/s (0 = unlimited).
        """
        return pulumi.get(self, "mbps_rd")

    @_builtins.property
    @pulumi.getter(name="mbpsRdMax")
    def mbps_rd_max(self) -> Optional[_builtins.float]:
        """
        Read burst throughput limit in MB/s; allows temporary bursts above MBpsRd.
        """
        return pulumi.get(self, "mbps_rd_max")

    @_builtins.property
    @pulumi.getter(name="mbpsWr")
    def mbps_wr(self) -> Optional[_builtins.float]:
        """
        Write throughput limit in MB/s (0 = unlimited).
        """
        return pulumi.get(self, "mbps_wr")

    @_builtins.property
    @pulumi.getter(name="mbpsWrMax")
    def mbps_wr_max(self) -> Optional[_builtins.float]:
        """
        Write burst throughput limit in MB/s; allows temporary bursts above MBpsWr.
        """
        return pulumi.get(self, "mbps_wr_max")


@pulumi.output_type
class EfiDisk(dict):
    """
    EFI disk configuration for the virtual machine.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "preEnrolledKeys":
            suggest = "pre_enrolled_keys"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in EfiDisk. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        EfiDisk.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        EfiDisk.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 efitype: _builtins.str,
                 storage: _builtins.str,
                 filename: Optional[_builtins.str] = None,
                 pre_enrolled_keys: Optional[_builtins.bool] = None):
        """
        EFI disk configuration for the virtual machine.

        :param _builtins.str efitype: EFI firmware size: '2m' (2 MB, legacy) or '4m' (4 MB, supports Secure Boot).
        :param _builtins.str storage: Target storage pool for the EFI disk (e.g., local-lvm).
        :param _builtins.str filename: File name of the EFI disk image (computed by Proxmox if not provided).
        :param _builtins.bool pre_enrolled_keys: Pre-enroll Microsoft and standard UEFI keys into the EFI firmware.
        """
        pulumi.set(__self__, "efitype", efitype)
        pulumi.set(__self__, "storage", storage)
        if filename is not None:
            pulumi.set(__self__, "filename", filename)
        if pre_enrolled_keys is not None:
            pulumi.set(__self__, "pre_enrolled_keys", pre_enrolled_keys)

    @_builtins.property
    @pulumi.getter
    def efitype(self) -> _builtins.str:
        """
        EFI firmware size: '2m' (2 MB, legacy) or '4m' (4 MB, supports Secure Boot).
        """
        return pulumi.get(self, "efitype")

    @_builtins.property
    @pulumi.getter
    def storage(self) -> _builtins.str:
        """
        Target storage pool for the EFI disk (e.g., local-lvm).
        """
        return pulumi.get(self, "storage")

    @_builtins.property
    @pulumi.getter
    def filename(self) -> Optional[_builtins.str]:
        """
        File name of the EFI disk image (computed by Proxmox if not provided).
        """
        return pulumi.get(self, "filename")

    @_builtins.property
    @pulumi.getter(name="preEnrolledKeys")
    def pre_enrolled_keys(self) -> Optional[_builtins.bool]:
        """
        Pre-enroll Microsoft and standard UEFI keys into the EFI firmware.
        """
        return pulumi.get(self, "pre_enrolled_keys")


@pulumi.output_type
class FileSourceRaw(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "fileData":
            suggest = "file_data"
        elif key == "fileName":
            suggest = "file_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in FileSourceRaw. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        FileSourceRaw.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        FileSourceRaw.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 file_data: _builtins.str,
                 file_name: _builtins.str):
        """
        :param _builtins.str file_data: The raw data in []byte
        :param _builtins.str file_name: The name of the file
        """
        pulumi.set(__self__, "file_data", file_data)
        pulumi.set(__self__, "file_name", file_name)

    @_builtins.property
    @pulumi.getter(name="fileData")
    def file_data(self) -> _builtins.str:
        """
        The raw data in []byte
        """
        return pulumi.get(self, "file_data")

    @_builtins.property
    @pulumi.getter(name="fileName")
    def file_name(self) -> _builtins.str:
        """
        The name of the file
        """
        return pulumi.get(self, "file_name")


@pulumi.output_type
class NumaNode(dict):
    """
    NUMA node topology configuration for the virtual machine.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "hostNodes":
            suggest = "host_nodes"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in NumaNode. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        NumaNode.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        NumaNode.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 cpus: _builtins.str,
                 host_nodes: Optional[_builtins.str] = None,
                 memory: Optional[_builtins.int] = None,
                 policy: Optional[_builtins.str] = None):
        """
        NUMA node topology configuration for the virtual machine.

        :param _builtins.str cpus: CPUs (and optionally threads) assigned to this NUMA node (e.g., 0-3).
        :param _builtins.str host_nodes: Host NUMA nodes to map to this virtual NUMA node (e.g., 0-1).
        :param _builtins.int memory: Memory in megabytes allocated to this NUMA node.
        :param _builtins.str policy: NUMA memory allocation policy (preferred, bind, interleave, or mpol).
        """
        pulumi.set(__self__, "cpus", cpus)
        if host_nodes is not None:
            pulumi.set(__self__, "host_nodes", host_nodes)
        if memory is not None:
            pulumi.set(__self__, "memory", memory)
        if policy is not None:
            pulumi.set(__self__, "policy", policy)

    @_builtins.property
    @pulumi.getter
    def cpus(self) -> _builtins.str:
        """
        CPUs (and optionally threads) assigned to this NUMA node (e.g., 0-3).
        """
        return pulumi.get(self, "cpus")

    @_builtins.property
    @pulumi.getter(name="hostNodes")
    def host_nodes(self) -> Optional[_builtins.str]:
        """
        Host NUMA nodes to map to this virtual NUMA node (e.g., 0-1).
        """
        return pulumi.get(self, "host_nodes")

    @_builtins.property
    @pulumi.getter
    def memory(self) -> Optional[_builtins.int]:
        """
        Memory in megabytes allocated to this NUMA node.
        """
        return pulumi.get(self, "memory")

    @_builtins.property
    @pulumi.getter
    def policy(self) -> Optional[_builtins.str]:
        """
        NUMA memory allocation policy (preferred, bind, interleave, or mpol).
        """
        return pulumi.get(self, "policy")


