// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { SdnApplyArgs } from "./sdnApply";
export type SdnApply = import("./sdnApply").SdnApply;
export const SdnApply: typeof import("./sdnApply").SdnApply = null as any;
utilities.lazyLoad(exports, ["SdnApply"], () => require("./sdnApply"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pve:sdnapply:SdnApply":
                return new SdnApply(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pve", "sdnapply", _module)
