// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { SDNApplyArgs } from "./sdnapply";
export type SDNApply = import("./sdnapply").SDNApply;
export const SDNApply: typeof import("./sdnapply").SDNApply = null as any;
utilities.lazyLoad(exports, ["SDNApply"], () => require("./sdnapply"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pve:sdnapply:SDNApply":
                return new SDNApply(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pve", "sdnapply", _module)
