// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ha

import (
	"context"
	"reflect"

	"errors"
	"github.com/hctamu/pulumi-pve/sdk/go/pve/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Proxmox HA resource that manages the HA configuration of a virtual machine in the Proxmox VE.
type HA struct {
	pulumi.CustomResourceState

	// The HA group identifier.
	Group pulumi.StringPtrOutput `pulumi:"group"`
	// The ID of the virtual machine that will be managed by HA (required).
	ResourceId pulumi.IntOutput `pulumi:"resourceId"`
	// The state of the HA resource (default: started).
	State pulumi.StringPtrOutput `pulumi:"state"`
}

// NewHA registers a new resource with the given unique name, arguments, and options.
func NewHA(ctx *pulumi.Context,
	name string, args *HAArgs, opts ...pulumi.ResourceOption) (*HA, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ResourceId == nil {
		return nil, errors.New("invalid value for required argument 'ResourceId'")
	}
	if args.State == nil {
		args.State = pulumi.StringPtr("started")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"resourceId",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource HA
	err := ctx.RegisterResource("pve:ha:HA", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHA gets an existing HA resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHA(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HAState, opts ...pulumi.ResourceOption) (*HA, error) {
	var resource HA
	err := ctx.ReadResource("pve:ha:HA", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering HA resources.
type haState struct {
}

type HAState struct {
}

func (HAState) ElementType() reflect.Type {
	return reflect.TypeOf((*haState)(nil)).Elem()
}

type haArgs struct {
	// The HA group identifier.
	Group *string `pulumi:"group"`
	// The ID of the virtual machine that will be managed by HA (required).
	ResourceId int `pulumi:"resourceId"`
	// The state of the HA resource (default: started).
	State *string `pulumi:"state"`
}

// The set of arguments for constructing a HA resource.
type HAArgs struct {
	// The HA group identifier.
	Group pulumi.StringPtrInput
	// The ID of the virtual machine that will be managed by HA (required).
	ResourceId pulumi.IntInput
	// The state of the HA resource (default: started).
	State pulumi.StringPtrInput
}

func (HAArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*haArgs)(nil)).Elem()
}

type HAInput interface {
	pulumi.Input

	ToHAOutput() HAOutput
	ToHAOutputWithContext(ctx context.Context) HAOutput
}

func (*HA) ElementType() reflect.Type {
	return reflect.TypeOf((**HA)(nil)).Elem()
}

func (i *HA) ToHAOutput() HAOutput {
	return i.ToHAOutputWithContext(context.Background())
}

func (i *HA) ToHAOutputWithContext(ctx context.Context) HAOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HAOutput)
}

// HAArrayInput is an input type that accepts HAArray and HAArrayOutput values.
// You can construct a concrete instance of `HAArrayInput` via:
//
//	HAArray{ HAArgs{...} }
type HAArrayInput interface {
	pulumi.Input

	ToHAArrayOutput() HAArrayOutput
	ToHAArrayOutputWithContext(context.Context) HAArrayOutput
}

type HAArray []HAInput

func (HAArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HA)(nil)).Elem()
}

func (i HAArray) ToHAArrayOutput() HAArrayOutput {
	return i.ToHAArrayOutputWithContext(context.Background())
}

func (i HAArray) ToHAArrayOutputWithContext(ctx context.Context) HAArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HAArrayOutput)
}

// HAMapInput is an input type that accepts HAMap and HAMapOutput values.
// You can construct a concrete instance of `HAMapInput` via:
//
//	HAMap{ "key": HAArgs{...} }
type HAMapInput interface {
	pulumi.Input

	ToHAMapOutput() HAMapOutput
	ToHAMapOutputWithContext(context.Context) HAMapOutput
}

type HAMap map[string]HAInput

func (HAMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HA)(nil)).Elem()
}

func (i HAMap) ToHAMapOutput() HAMapOutput {
	return i.ToHAMapOutputWithContext(context.Background())
}

func (i HAMap) ToHAMapOutputWithContext(ctx context.Context) HAMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HAMapOutput)
}

type HAOutput struct{ *pulumi.OutputState }

func (HAOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**HA)(nil)).Elem()
}

func (o HAOutput) ToHAOutput() HAOutput {
	return o
}

func (o HAOutput) ToHAOutputWithContext(ctx context.Context) HAOutput {
	return o
}

// The HA group identifier.
func (o HAOutput) Group() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HA) pulumi.StringPtrOutput { return v.Group }).(pulumi.StringPtrOutput)
}

// The ID of the virtual machine that will be managed by HA (required).
func (o HAOutput) ResourceId() pulumi.IntOutput {
	return o.ApplyT(func(v *HA) pulumi.IntOutput { return v.ResourceId }).(pulumi.IntOutput)
}

// The state of the HA resource (default: started).
func (o HAOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *HA) pulumi.StringPtrOutput { return v.State }).(pulumi.StringPtrOutput)
}

type HAArrayOutput struct{ *pulumi.OutputState }

func (HAArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*HA)(nil)).Elem()
}

func (o HAArrayOutput) ToHAArrayOutput() HAArrayOutput {
	return o
}

func (o HAArrayOutput) ToHAArrayOutputWithContext(ctx context.Context) HAArrayOutput {
	return o
}

func (o HAArrayOutput) Index(i pulumi.IntInput) HAOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *HA {
		return vs[0].([]*HA)[vs[1].(int)]
	}).(HAOutput)
}

type HAMapOutput struct{ *pulumi.OutputState }

func (HAMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*HA)(nil)).Elem()
}

func (o HAMapOutput) ToHAMapOutput() HAMapOutput {
	return o
}

func (o HAMapOutput) ToHAMapOutputWithContext(ctx context.Context) HAMapOutput {
	return o
}

func (o HAMapOutput) MapIndex(k pulumi.StringInput) HAOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *HA {
		return vs[0].(map[string]*HA)[vs[1].(string)]
	}).(HAOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HAInput)(nil)).Elem(), &HA{})
	pulumi.RegisterInputType(reflect.TypeOf((*HAArrayInput)(nil)).Elem(), HAArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*HAMapInput)(nil)).Elem(), HAMap{})
	pulumi.RegisterOutputType(HAOutput{})
	pulumi.RegisterOutputType(HAArrayOutput{})
	pulumi.RegisterOutputType(HAMapOutput{})
}
