// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as acl from "./acl";
import * as config from "./config";
import * as group from "./group";
import * as ha from "./ha";
import * as pool from "./pool";
import * as role from "./role";
import * as storage from "./storage";
import * as types from "./types";
import * as user from "./user";
import * as vm from "./vm";

export {
    acl,
    config,
    group,
    ha,
    pool,
    role,
    storage,
    types,
    user,
    vm,
};
pulumi.runtime.registerResourcePackage("pve", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:pve") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
